### ISSUE TITLE
New File Wizard to create a Swagger file

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#1]

**Comment by tfesenko** [comment]
@ghillairet provided the initial implementation
Opening a wizard:
<img width="574" alt="screen shot 2015-10-02 at 12 48 41 pm" src="https://cloud.githubusercontent.com/assets/644582/10252394/37888ce0-6905-11e5-9e4a-cd00755f44be.png">
The wizard:
<img width="583" alt="screen shot 2015-10-02 at 12 48 50 pm" src="https://cloud.githubusercontent.com/assets/644582/10252396/378bf98e-6905-11e5-8460-24ed3935606d.png">
The wizard opens a file with basic pre-populated contents:
<img width="423" alt="screen shot 2015-10-02 at 12 49 04 pm" src="https://cloud.githubusercontent.com/assets/644582/10252395/378b750e-6905-11e5-8a7f-beaf82098be3.png">

**Comment by tfesenko** [comment]
@ghillairet , the Wizard header (see the second screenshot) says that a file with a `*.yml` extension will be created, while the actual file has the `*.yaml`, not `*.yml` extension

**Comment by ghillairet** [comment]
I fixed the extension.
