### ISSUE TITLE
Provide built plugin jars

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#10]
As a temporary solution until #7 "Publish SwagEdit" is implemented, we want to provide an easy way for our team to try SwagEdit. An easy way means that they don't need to checkout sources and launch SwagEdit from Eclipse, but can simply copy the jars into the dropins directory.

**Comment by ghillairet** [comment]
Building an update site can already be done by running a maven command. I updated the README with the instructions. The update site can be publish somewhere, just tell me if we have a server for that.

**Comment by tfesenko** [comment]
Following steps described on https://github.com/ModelSolv/SwagEdit produced a valid update site which I was able to install to RepreZen. 
So, 
1. The description is correct
2. SwagEdit is compatible with RepreZen
