### ISSUE TITLE
Address code review comments in PR #85, better `oneOf` error messages.

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#111]
PR #85 has some issues that have not been addressed yet.  We want to close the associated issue #60, so I'm extracting this to a separate issue with a much narrower scope.

@tfesenko, I'm adding it to the SwagEdit open source release milestone.  If you think it's not important enough to address in this scope, you can put it on the backlog.

**Comment by tfesenko** [comment]
Addressed in PR https://github.com/RepreZen/SwagEdit/pull/110
