### ISSUE TITLE
Finalize version 0.8 for SwagEdit release

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#112]

**Comment by tfesenko** [comment]
When we are ready to change the version we can run this command and commit the changes:

```
mvn org.eclipse.tycho:tycho-versions-plugin:set-version -DnewVersion=1.0.0-SNAPSHOT
```

**Comment by tedepstein** [comment]
Changed to 0.8 per discussion on slack.

**Comment by tfesenko** [comment]
Done, first v0.8 update site available on http://products-internal.reprezen.com/swagedit/0.8.0.201705091743/
Integration with RepreZen in https://github.com/ModelSolv/RepreZen/pull/1280
