### ISSUE TITLE
Code assist for External references

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#115]
Swagger allows JSON Refs to refer to external files, or definitions contained in external files.  It would be helpful for code assist to support this.  The exact behavior would need to be specified more completely, but as a strawman proposal:
- Should work like Code assist suggestion list cycling in the JDT.  Ctrl+Space brings up the first suggestion list.  Repeating Ctrl+Space cycles through the available suggestion lists.<br/><br/>
- Suggestion Lists should include:
  - Current file only
  - Current project
  - Workspace<br/><br/>
- The "Current Project" and "Workspace" suggestion lists should only include Swagger specs in the `Models` folder and its subfolders.  They should not include any Swagger specs that might exist in the `GenTargets` subfolder.<br/><br/>
- I don't think we need preferences to control this now, though later we could introduce preferences to customize the suggestion lists and their order.<br/><br/>
- Should work for schema definitions, path items, parameters and response references.<br/><br/>
- I think the suggestion list format for ref should change.  It currently looks like this:<br/>   <br/>
  ![image](https://cloud.githubusercontent.com/assets/692813/16423165/f53ba5cc-3d28-11e6-81c8-5cd5515007c6.png)
  <br/><br/>The word "ref" after the name is not very helpful.  I think it should show the actual text that's going to be inserted.  So for Pet, the entry should be:<br/><br/>    **Pet:** "#/definitions/Pet"<br/><br/>This also lets the user distinguish same-named definitions from different files.

**Comment by ghillairet** [comment]
Ok those requirements are clear for me, I have no particular questions about this for now, I'll start to implement a first version and see if requirements need to be redefined.

**Comment by ghillairet** [comment]
I got a first version working that works only for references to definitions. Repeating Ctrl + Space does create the different lists (Local, Project, Workspace). You can see it working in this screencast.

![refs](https://cloud.githubusercontent.com/assets/148045/16654801/bec35004-4457-11e6-8035-a9dc349d74d4.gif)

**Comment by ghillairet** [comment]
@tedepstein @tfesenko About lists, in the current implementation the first list contains only element from the current file, the second list contains elements from files in the same project (excluding elements from current file) and last contains elements from files in all workspace (but does include elements from current project). Should the last list not contain elements from current project?

> The "Current Project" and "Workspace" suggestion lists should only include Swagger specs in the Models folder and its subfolders. They should not include any Swagger specs that might exist in the GenTargets subfolder.

Are the files in the GenTargets folder marked with a derived flag? That would be a nicer way to exclude those as I assume not all SwagEdit users would put their files in such folders.

**Comment by ghillairet** [comment]
@tedepstein Does references to path items, parameters or responses can be local? Or is it only for external files.

**Comment by tfesenko** [comment]
The screencast looks good, @ghillairet !

> Should the last list not contain elements from current project?

@tedepstein what's your opinion? Should the last list be a superset of the first two + elements from other projects in the workspace?

> Are the files in the GenTargets folder marked with a derived flag?

They are not. We will consider setting "derived" for the GenTarget output folder.

**Comment by tedepstein** [comment]
@ghillairet, @tfesenko:

Each list should be a superset of the previous one in the sequence:
- Current file only
- Current project, _including_ current file
- Current workspace, _including_ current project.

> Are the files in the GenTargets folder marked with a derived flag? That would be a nicer way to exclude those as I assume not all SwagEdit users would put their files in such folders.

Good point.  Is "derived" a standard file or folder attribute in Eclipse? If so, we could use that.  Otherwise, instead of restricting this to the `models` folder, we could explicitly exclude the `genTargets` folder, but include everything else.

> Does references to path items, parameters or responses can be local? Or is it only for external files.

path items are only useful when the path item resides in an external file, so it's safe to say that they cannot be local.

parameters and responses can be local or external.

**Comment by tedepstein** [comment]
@ghillairet thanks for the screencast.  Good to see this working!

One feature request:  I would like to include a prompt at the bottom of the suggestion list, like in the JDT:

![image](https://cloud.githubusercontent.com/assets/692813/16661378/a98a303e-4440-11e6-87be-0e716097a5dd.png)

![image](https://cloud.githubusercontent.com/assets/692813/16661389/b77f046c-4440-11e6-9d73-1107cb8413f6.png)

The prompt shows the next suggestion list in the cycle.  So the prompts should be as follows:

| When Showing | Prompt Says |
| --- | --- |
| File References | Press 'Ctrl+Space' to show all schemas in the project. |
| Project References | Press 'Ctrl+Space' to show all schemas in the workspace. |
| Workspace References | Press 'Ctrl+Space' to show schemas in the current file. |

Two parts of the prompt are dynamic:
1. The key combination, which has platform-specific defaults, and which the user can override.  I tested and verified that the JDT actually does detect the assigned shortcut key, and displays that key combination correctly in the prompt at the bottom of the suggestion list.  We should do the same thing.
2. The item type whose definitions are shown in the suggestion list.  This should be one of the following:
- schemas
- parameters
- responses
- path items

**Comment by ghillairet** [comment]
I added the text messages and the proposals for parameters, responses and path items. There could be some little bugs to fix, and tests to add, but overall it's working.

**Comment by ghillairet** [comment]
PR that fixes the remaining issues https://github.com/RepreZen/SwagEdit/pull/152

**Comment by tfesenko** [comment]
All related pull requests are merged to master, passed QA.

**Comment by tfesenko** [comment]
I found that cycling code-assist works correctly for parameters and pathItems, but not for schemas - only local definitions are shown, definitions from other files are not displayed when expected.
I think it worked yesterday, so it might be related to recent refactoring.

**Comment by ghillairet** [comment]
@tfesenko I don't seem to find the case where code assist for schema definitions do not work.
