### ISSUE TITLE
SwagEdit does not detect some validation errors in some array schemas

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#116]
From @andylowry:

Attached are two files - ropeSwagger.yaml and ropeSwagger-fixed.yaml. Where they differ, there are comments containing "FIXED" pointing out a problem with the former that is fixed in the latter. Each problem is a violation of the swagger spec, but none are detected by SwagEdit. There are likely other validation errors that are not currently detected, so analysis should probably precede attempts to fix these specific issues.

**Comment by tedepstein** [comment]
[errors.zip](https://github.com/RepreZen/SwagEdit/files/226082/errors.zip)

**Comment by tedepstein** [comment]
Test -- Adding a comment

**Comment by tfesenko** [comment]
@tedepstein this is an example of validations that SwagEdit should be performing, but currently is not.

**Comment by tedepstein** [comment]
@tfesenko , can you please review and post back here if there are still known problems that SwagEdit doesn't detect?

**Comment by tfesenko** [comment]
Did not detect the following FIXME items:

## Schema for an `Array`

Related: #123 

Line 1365: missing "items" property; "$ref" was a direct child of "schema"

``` yaml
          schema:
            type: array
            $ref: "#/definitions/sessionResponseSchema" 
```

Line 1427: $ref property had leading "- " making it a singleton array

``` yaml
    type: array

    items:
      - $ref: #/definitions/addressResponseObjectSchema 
```

## 

Line 1580: type property was missing
(similar with line 2148)

``` yaml
    items:  

      # throughout, sbm made up what is required
      required:
        - input_index
```

**Comment by ghillairet** [comment]
@tedepstein @tfesenko See PR #236 

I added some validation that check for these:
- missing type information for object schema definition
- wrong type definition if the definition should be an object (ex properties field is present but type is string) 
- missing properties field when a required field is present
- invalid required property

You can see the related tests here https://github.com/RepreZen/SwagEdit/commit/3d4ca8f28830271a49ed15a15077460704b5cad0#diff-bab1306f3a15280d552d52440a4d0ef1R530

**Comment by tedepstein** [comment]
@tfesenko , can we close this issue?  

For the record, you mentioned one type of problem that I just confirmed is prohibited by the Swagger 2.0 spec:

> Line 1427: $ref property had leading "- " making it a singleton array
> 
> ```
>     type: array
>     items:
>       - $ref: #/definitions/addressResponseObjectSchema 
> ```

In JSON Schema, Arrays are actually allowed to have a list of schemas as the value of 'items'.  The effect is that the array becomes a strongly typed tuple. So given this schema:

```
  type: array
  items:
   - type: string
   - type: integer
   - type: integer
```

This would be a valid value:

```
  [
    "Florida",
    53,
    28
  ]
```

However, Swagger does not allow the value of `items` to be an array of schema objects.  It only allows `items` to be a single `Items Object`:

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#user-content-parameterItems

So you're right, we should enforce that, if we're not already doing it.  However, this one validation does not need to be high-priority.

**Comment by tfesenko** [comment]
Validation detects the cases from https://github.com/RepreZen/SwagEdit/issues/116#issuecomment-235304884

But with the new validation rules the attached `ropeSwagger-fixed.yaml` now has validation errors, mostly because of missing types, "required" properties listing properties that don't exist, and `$ref: #/definitions/addressResponseObjectSchema` needs quotes for its value.
