### ISSUE TITLE
Warn on duplicate properties

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#117]
Between, JSON, YAML and Swagger, there are some different rules and guidelines about duplicate property names; and implementations vary.

But a duplicate property name is almost always a user error, so SwagEdit should warn in this instance.

**Comment by tedepstein** [comment]
@tfesenko, also flagging this as high priority.

**Comment by ghillairet** [comment]
The branch task/117 contains a preliminary implementation to support warning on duplicate keys. It works on objects. Need to see what other kind of values should be supported (ex duplicate items in arrays?).

![screen shot 2016-05-19 at 16 06 02](https://cloud.githubusercontent.com/assets/148045/15396420/5776ac6c-1ddc-11e6-9dad-239eb1dcfd9a.png)

**Comment by tfesenko** [comment]
@tedepstein , we need your feedback on phrasing, see the screenshot above

**Comment by tedepstein** [comment]
I'd recommend the following error message:

> Duplicate key: the object [object name] has more than one property named [property name]

**Comment by tedepstein** [comment]
@ghillairet asked:

> Need to see what other kind of values should be supported (ex duplicate items in arrays?).

I think this should be limited to duplicate property names in an object.  Duplicate array values are allowed, and should not cause a problem.

**Comment by tfesenko** [comment]
The PR merged, but I am leaving this issue open.
The suggested phrasing for the error message was :

> Duplicate key: the object [object name] has more than one property named [property name]

The actual is: 

> error_duplicate_keys = object has duplicate keys: %s
> <img width="346" alt="screen shot 2016-05-30 at 8 37 04 pm" src="https://cloud.githubusercontent.com/assets/644582/15660168/8001dc2e-26a6-11e6-9fa7-d0fe65863803.png">

**Comment by ghillairet** [comment]
I changed the message to `Duplicate key: the object has more than one property named %s`
It does not include the object name, how should we named an object?

**Comment by tedepstein** [comment]
I think we can leave this as you've done it, without an object name.

**Comment by tfesenko** [comment]
<img width="501" alt="screen shot 2016-06-02 at 6 29 47 pm" src="https://cloud.githubusercontent.com/assets/644582/15763173/03885898-28f0-11e6-8f6f-a85a436ee66f.png">
