### ISSUE TITLE
Deprecate unqualified names as abbreviated JSON Ref syntax

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#119]
As discussed in https://github.com/ModelSolv/RepreZen/pull/923

@andylowry wrote:

> I've learned that the whole "simple ref" idea in swagger (e.g. "$ref: Pet" instead of "$ref: '#/definitions/Pet'") is considered officially unsupported in Swagger 2.0. There is still vestigial code in some swagger projects that implement it, but there shouldn't be. The intention now is that refs in swagger specs precisely follow JSON Ref requirements.

@tedepstein wrote: 

> This is a major change that affects SwagEdit as well as multiple components of API Studio. @andylowry, can you point us to the source where you learned about this? Are you sure it applies to Swagger–OpenAPI 2.0 (the current version) and not to OpenAPI, the next version?
> 
> I am almost sure that many of the Swagger examples (in the spec and in various quasi-official places) used the abbreviated syntax. That, combined with "vestigal" tool support probably means that there are many Swagger specs in the wild that use this syntax. If we remove support for it, it will make things difficult for our users who want to import existing Swagger specs into API Studio, or reference components of them (schema objects, parameters, responses, paths).

In addition to our validation, this affects code assist and possibly code templates.

**Comment by andylowry** [comment]
Copied from ModelSolv/RepreZen#923
@tedepstein wrote:

> @andylowry, can you point us to the source where you learned about this? Are you sure it applies to Swagger–OpenAPI 2.0 (the current version) and not to OpenAPI, the next version?

You'll find it here: https://groups.google.com/forum/#!searchin/swagger-swaggersocket/Simple$20Refs$20dead/swagger-swaggersocket/35rK42NK5oY/Dc5erFjfMgAJ

The responses are pretty definitive, and the OpenAPI-Specification github project (the source of our swagger examples) got rid of simple refs a while back (but we grabbed them earlier, so we've got them in our examples).

> We can look into this further, but I think it's better to treat this as a warning, not rip out the supporting code. I'll open an issue for this in SwagEdit, and we can discuss further in that context.

I'd like to at least move to using a narrower test for simple refs right away - e.g. a a single "name" with no path separators or other URL syntax characters. So "Pet" would be an acceptable simple ref, but "Pet.yaml", "Pet/index.yaml", "file:///a/b/c.yaml" would not (astonishingly, by the old rules as implemented by the swagger parser, they are ALL interpreted as simple refs). Attempts to use such things in our current implementation would fail.

**Comment by tedepstein** [comment]
Specific tasks related to this in SwagEdit:
- Warning on short-form references, distinct from standard validation warning.  The text should say:  "Simplified reference syntax is deprecated. The reference should be a valid JSON pointer."
- Ensure simple references are not used in the boilerplate text included in the New Swagger Spec command.
- Use full JSON Pointer syntax in code assist (already completed).

**Comment by tedepstein** [comment]
@tfesenko , I've made this one high priority, and clarified scope in my last comment.  I'll address the API Studio example wizard separately, in a Jira issue.

**Comment by tfesenko** [comment]
Current state:
- [ ] Warning on short-form references, distinct from standard validation warning. The text should say: "Simplified reference syntax is deprecated. The reference should be a valid JSON pointer."
  We show a warning with a generic message:
  <img width="1016" alt="screen shot 2016-07-26 at 11 09 59 am" src="https://cloud.githubusercontent.com/assets/644582/17143544/99c9fbda-5321-11e6-8272-d2805a970073.png">
- [x] Ensure simple references are not used in the boilerplate text included in the New Swagger Spec command.
  Done
- [x] Use full JSON Pointer syntax in code assist (already completed).
  Done

**Comment by tfesenko** [comment]
Extracted #203 Warning message on short-form references 
Closing this issue
