### ISSUE TITLE
Hyperlink support ("go to definition")

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#120]
Provide hyperlink support: Ctrl+click or select+F3 to navigate to a referenced element (e.g. a schema object, parameter, response or path).

There are three major cases:
1. Reference to an element from the same file, 
2. Reference to an element from an external file from the workspace:
   - Located in the same project as the root Swagger file
   - From another project
3. Reference to an element outside of workspace, e.g. referenced using http 
   - the main issue extracted to #121, in the scope of #120 it's sufficient to fail gracefully - disable the navigation or provide an informative message.
## Paths: Relative path, optional support for  absolute paths

This example uses only relative paths, and we expect it to be the main use case (note that URIs in references are covered by another issues). So, cases like "./foo" or "../pizza" must be supported. Support for absolute path is not important right now. If it's really easy to support them, then we can do it now, otherwise we can postpone it.
## Referenced files: Swagger, arbitrary YAML optional

Note that all files are valid Swagger files, that's why you can see strange things like "paths: {}" in the parameters file, paths must be specified, but it can be an empt list. We must provide support for external references to valid Swagger files. For other YAML files is optional: implement it if it's easy to do, ignore them otherwise. So, support for the PetStoreSeparate example is not required in this iteration.

**Comment by ghillairet** [comment]
I started to work on this issue, the commit contains preliminary implementation of HyperlinkDetector and IHyperlink. Those will be used to detect elements inside a document that are links and how to open them.

**Comment by ghillairet** [comment]
Update on this, below a preview of what the current implementation does.

![hyperlinks](https://cloud.githubusercontent.com/assets/148045/15150741/c130df48-16ce-11e6-8998-d6ff65c792fd.gif)

**Comment by tedepstein** [comment]
Looks good, @ghillairet !  Will it work with an internal reference path, like `#/definitions/TaxFilingObject`?

**Comment by ghillairet** [comment]
Eventually it will, the current version does not handle all cases.

**Comment by tedepstein** [comment]
OK, thanks.  The OpenAPI spec maintainers have told us that they are deprecating the simplified form of JSON Refs, using only the name.  Future Swagger tooling will only support properly qualified internal, relative or external refs.

I expect this will phase out over time, because there are already many Swagger specs "in the wild" that use the simplified reference form.  But we will need to change our code assist to use the full path for internal refs, and will want to make sure that the hyperlink feature supports this form.

**Comment by tedepstein** [comment]
BTW, @andylowry , can you please point us to the OpenAPI issue or conversation thread where we learned that the simplified ref form is being deprecated?

**Comment by ghillairet** [comment]
@tfesenko send me a link about that, should be this one https://groups.google.com/forum/#!searchin/swagger-swaggersocket/Simple$20Refs$20dead/swagger-swaggersocket/35rK42NK5oY/Dc5erFjfMgAJ

**Comment by tedepstein** [comment]
Right, and @andylowry provided further detail in #119.  Sorry for repeating the question.

**Comment by tfesenko** [comment]
The navidation selects the entire reference element in YAML to make it more prominent. The default Eclipse selection color is used.

This is how it looks like with the standard RepreZen EditBox configuration:
![opendefinition_weditbox](https://cloud.githubusercontent.com/assets/644582/15184969/407a002c-1765-11e6-8b8c-01d73911ca29.gif)

**Comment by ghillairet** [comment]
I started to work on hyperlinks to other yaml files, it works for yaml files inside the workspace. It will open the swagger editor if it's a swagger file or default to yedit for other yaml files.

![hyperlinks](https://cloud.githubusercontent.com/assets/148045/15363075/c4b2ce3e-1d17-11e6-9706-d659db4b1e30.gif)

**Comment by tedepstein** [comment]
Closing this issue.  Any remaining work should go into separate issues.
