### ISSUE TITLE
Array without items is disallowed by Swagger, should be shown as a validation error

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#123]
While JSON Schema allows an array without an "items" schema, Swagger explicitly disallows this.  We should adjust the schema so that it shows a validation error in this case.

**Comment by tfesenko** [comment]
@tedepstein this issue is "high priority", but it's in the "Backlog" milestone issues from which we don't include to our filters. Should I move it to "SwagEdit Open-Source release" instead?

**Comment by tedepstein** [comment]
Yes, please move it to a current milestone so it shows up in your views.

**Comment by tfesenko** [comment]
As I understand it, this should show a validation error on the `Pets`:

``` yaml
  Pets:
    type: array
  NextStructure: <...>
```

**Comment by tedepstein** [comment]
Yes, correct.

**Comment by tedepstein** [comment]
Yes @tfesenko , that's correct.

**Comment by ghillairet** [comment]
Started to work on this in PR #222 

Current validation message is `Array without items is disallowed by Swagger, should be shown as a validation error`

![array](https://cloud.githubusercontent.com/assets/148045/19278849/3d8ae852-8fdf-11e6-847a-b84c2acd58e0.gif)
