### ISSUE TITLE
Invalid JSON Example shown at top level as "object has missing required properties"

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#125]
Reported by Saul in [support ticket #111](https://support.reprezen.com/helpdesk/tickets/111):

In the project attached to the support ticket, the file `/models/PathItems/ropeSwagger_company_&companyId_serviceable_&serviceableId_products.json.yaml` has invalid json in its example, starting on line 46.

It's shown as a schema validation problem:

```
Multiple markers at this line
- object has missing required properties "info", "paths", "swagger"
- 44 changed lines
```

The invalid JSON seems to have made SwagEdit unable to parse the file correctly, so the error message doesn't point to the issue correctly.  

It would be better if we could report more accurately what caused the problem.

**Comment by tedepstein** [comment]
Emerged again in https://support.reprezen.com/helpdesk/tickets/124

**Comment by tedepstein** [comment]
Discussed in [ZEN-2407](https://modelsolv.atlassian.net/browse/ZEN-2407).  Marking as high priority.  A parse failure needs to be identified as such, otherwise it becomes a support issue.

**Comment by ghillairet** [comment]
What was the problem in the JSON example? I made a screencast showing the errors when invalid JSON is present.

![json](https://cloud.githubusercontent.com/assets/148045/16876592/bef9634e-4aa4-11e6-8500-ae1edbe610cf.gif)

**Comment by tfesenko** [comment]
I am able to reproduce this issue:
<img width="428" alt="screen shot 2016-07-15 at 10 22 59 am" src="https://cloud.githubusercontent.com/assets/644582/16877460/2e79df66-4a76-11e6-92d4-49e3cb5a4b5d.png">

@ghillairet I will try to create a simplified model for you to demonstrate this issue.

**Comment by tfesenko** [comment]
This model creates yields an "Unable to read contents error". It contains a valid JSON wrapped in extra curly braces.
Note that the error message is more helpful that the one which was originally reported.

The error is shown on the first line:
<img width="714" alt="screen shot 2016-07-15 at 10 42 56 am" src="https://cloud.githubusercontent.com/assets/644582/16878056/0517d26a-4a79-11e6-85aa-9655c839e3d5.png">

``` yaml
---
swagger: "2.0"
info:
  description: Tax Blaster
  version: 1.0.0
  title: TaxBlaster
host: taxblaster.com
basePath: /api
schemes:
- http

tags:
- name: TaxFilingObject
  description: An individual Tax Filing record, accessed by its ID

paths:

  /taxFilings/{id}:

    # Operations are identified by an HTTP method.  
    get:
      tags:
      - TaxFilingObject
      description: Retrieves a tax filing having the specified id.
      operationId: getTaxFiling
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        description: ID of the requested TaxFiling
        required: true
        type: string
      responses:
        200:
          description: Successful response, with a representation of the Tax Filing.
          schema:
            # Reference to a Schema Object described in 'definitions' section
            $ref: "#/definitions/TaxFilingObject"
          examples:
            {"application/json": 
              {{
                    "1": {
                      "productId": 1
                    }
                  }
               }  }   
        404:
          description: The requested tax filing was not found.

definitions:
  TaxFilingObject:
    type: object
    description: An individual Tax Filing record.
    properties:
      filingID:
        type: string
```

**Comment by tedepstein** [comment]
@tfesenko , in your last example, which line has the error marker?

**Comment by ghillairet** [comment]
@tfesenko I have the same error at the top of the document, but I'm not sure that's the same issue as the original issue. It seems that in the original the document can be parse, it's not the case in your example. 
Maybe it has to do with changes that happened in validation related code since this issue was open.

**Comment by tedepstein** [comment]
You might also want to try the provided examples on Windows.  Sorry that I am unavailable to help with this right now, just need to prepare for Demo Day.

**Comment by tfesenko** [comment]
@tedepstein wrote:

>  in your last example, which line has the error marker?

It's the first line. I updated my comment above with a screenshot.

@ghillairet wrote:

> I have the same error at the top of the document, but I'm not sure that's the same issue as the original issue. It seems that in the original the document can be parse, it's not the case in your example. 

I see exactly the same error as in the original model. It's just that this model is _a little bit_ smaller.

**Comment by tedepstein** [comment]
If it's possible to put the error marker on (or close to) the line that has
the error, that would be better.  Otherwise the user may not know where to
look for the problem.  Can a parser error like this give some indication of
the error location?

**Comment by ghillairet** [comment]
@tfesenko It looks like in your example, the error comes from the parsing of the document as JSON and not during the parsing as YAML. Error is not shown correctly because markers are not created yet from JSON parsing exception.

**Comment by tfesenko** [comment]
Ok, maybe I just discovered another issue. 
@ghillairet , anyway, you have the original model.

**Comment by ghillairet** [comment]
PR https://github.com/RepreZen/SwagEdit/pull/157 adds error markers for JSON exceptions.

**Comment by tfesenko** [comment]
The location of the error is shown correctly, but the error description can be improved.
Merging the PR and leaving this issue open for now.
