### ISSUE TITLE
NPE when opening Swagger file

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#127]
Very little information available on this bug report, which came through an Intercom chat from an anonymous user, whom we can no longer reach.

But there might be enough here to tell us about an area of the code that needs to be made more robust:

> Hello
> I am just installed RepreZen API Studio
> It looks promising to update my yaml
> But for whatever yml I am opening:
> java.lang.NullPointerException at com.reprezen.swagedit.editor.SwaggerEditor.doSetInput(SwaggerEditor.java:180)
> Where can log the issue? Any further information you may need?
> *I have just..
> Unexpected error while loading repository template extensions

**Comment by tedepstein** [comment]
@tfesenko or @ghillairet, if you look at the referenced code, do you think there's a way to prevent the NPE, so we can present a more helpful error message or error marker in the editor?

**Comment by tfesenko** [comment]
The NPE is thrown in 

``` java
getDocumentProvider().getDocument(getEditorInput()).addDocumentListener(changeListener);
```

because `getDocumentProvider().getDocument()` can return `null` is some cases. The `changeListener` validates the model on change. 

`getDocumentProvider().getDocument(unput)`  returns `null` when the `input` is null.
I will check other cases when and why `getDocumentProvider().getDocument()` can return null.

**Comment by tedepstein** [comment]
NPE was also reported by Saul in this support ticket:
https://support.reprezen.com/helpdesk/tickets/110

So I think this bug is real, and we should code defensively to prevent it.  I'll mark this as high priority, as one of the bugs we should fix before adding more navigation conveniences.

**Comment by ghillairet** [comment]
See PR https://github.com/RepreZen/SwagEdit/pull/130 for a fix to that exception.

**Comment by tfesenko** [comment]
The PR merged. Straightforward changes.
