### ISSUE TITLE
Go To Definition:  Support Path References

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#129]
Path References don't seem to be supported yet.  These are difficult because of the required substitutions.  At a minimum, path parameters will contain `~1` sequences, which are tokens for forward slashes.  Other substitutions are discussed in #59, and some of these can cause the URI to be invalid.  

Still, to the extent possible, we would like to support these eventually.

**Comment by ghillairet** [comment]
I confirm this is not working in branch master, but it does in branch 59.
The format for a $ref to a path should be like:

```
$ref: '#/paths/~1pets~1{id}'
```

This will point to

``` yaml
paths:
  '/pets/{id}':
```

**Comment by tedepstein** [comment]
OK, I see that there's some work on task/59 and task/59-json-pointers that hasn't been merged yet.  So I'll re-test after you've opened a pull request for #59 and we've merged these changes.

**Comment by tedepstein** [comment]
This works now.
