### ISSUE TITLE
New Swagger file wizard: .yaml extension should be added automatically

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#13]
1. Invoke the New Swagger File wizard
2. Type "MyModel" in the field "File name". It's allowed. 
3. Finish the wizard

A new file named "MyModel" will be created. 
I think it's a right thing to allow omitting the extension in the wizard, but I expect to get a file with .yaml extension - MyModel.yaml in this case.

**Comment by ghillairet** [comment]
Should be fixed now.
Also updated the wizard to have a more standard UI.

**Comment by tfesenko** [comment]
Fixed
