### ISSUE TITLE
Choose License (currently EPL)

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#14]
When you install SwagEdit from an update site, a license agreement is presented. Currently it's EPL, you can view and edit it in [SwagEdit/com.reprezen.swagedit.feature/featur.xml](https://github.com/ModelSolv/SwagEdit/blob/master/com.reprezen.swagedit.feature/feature.xml) .

**Comment by tedepstein** [comment]
@tfesenko , EPL is fine with me.  Please close this issue unless there is any additional work to do.

**Comment by tfesenko** [comment]
The license description is provided in SwagEdit feature. The EPL info is displayed when installing via an update site.
Closing
