### ISSUE TITLE
Failure to detect broken references

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#142]
Saul posted a multi-file project with some broken references that were not detected by validation.  These were mostly due to case-sensitivity, but reference validation should be case-sensitive, otherwise Swagger specs will not be portable.

**Comment by ghillairet** [comment]
I have made a PR for this, see https://github.com/RepreZen/SwagEdit/pull/146
@tfesenko Please have a look to see if it does what is needed.
