### ISSUE TITLE
Complete Code Assist Cycling for External References

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#149]
Comments in the PR still need to be addressed, and in particular the type of object reference (schema, response, parameter or path item) needs to be made dynamic in the prompt.

**Comment by ghillairet** [comment]
This is done in this PR https://github.com/RepreZen/SwagEdit/pull/152

The text message is now updated depending on the context it's been called.
Screenshots showing the updates on the prompt messages:

Message for schema definitions
![screen shot 2016-07-14 at 17 24 04](https://cloud.githubusercontent.com/assets/148045/16845083/e8307ae4-49e7-11e6-8332-ac9399486649.png)

Message for path items
![screen shot 2016-07-14 at 17 24 12](https://cloud.githubusercontent.com/assets/148045/16845091/f2311490-49e7-11e6-8841-db780488b78d.png)

**Comment by tedepstein** [comment]
@tfesenko , marking this complete, based on my testing of the last release build.
