### ISSUE TITLE
External reference shows warning

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#150]
Related to [ZEN-2780](https://modelsolv.atlassian.net/browse/ZEN-2780).

In the attached workspace, I used the new Code Assist cycling feature in SwagEdit to insert a reference to a schema object defined in an external file. Uber.yaml has a reference to the Pets schema object in Pet Store.yaml. The reference looks correct to me, but SwagEdit shows a warning, and the Doc View shows a rendering error.

[RepreZen workspace cycling.zip](https://github.com/RepreZen/SwagEdit/files/361967/RepreZen.workspace.cycling.zip)

<img width="967" alt="reprezen - ubermodelsuber yaml - reprezen api studio_2016-07-13_12-31-38" src="https://cloud.githubusercontent.com/assets/692813/16811595/20dfd8cc-48f7-11e6-9381-647c674cd36c.png">

**Comment by tfesenko** [comment]
As @andylowry pointed in ZEN-2780:

> Reference is invalid. The "URL" part of the reference must conform to URI syntax, which does not permit space characters. The relative URL should be url-escpaped when creating the URL (i.e. this is something content-assist needs to pay attention to). Change "Pet Store" to "Pet%20Store" and all works as expected.

Code-assist should insert a valid URL-escaped strings for refs

**Comment by tedepstein** [comment]
So, as discussed, there are two things to be fixed in SwagEdit:
1. Code Assist should replace spaces with %20.
2. References with illegal URI syntax should be treated as an error, not a warning. This is different from legal URI that cannot be resolved, or that does not resolve to a valid object of the expected type. Unresolvable references are still warnings; illegal URIs are errors.

That latter issue is important so that the live views don't try to render an invalid swagger doc, throw and exception, and display the last-resort "Rending Error."

**Comment by ghillairet** [comment]
PR https://github.com/RepreZen/SwagEdit/pull/151

**Comment by tfesenko** [comment]
The major part is done, please correct the error message to close this issue.

**Comment by ghillairet** [comment]
The message has been updated in this PR https://github.com/RepreZen/SwagEdit/pull/153
