### ISSUE TITLE
Xtend-compilation error in tests

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#17]
`mvn clean verify` fails during Xtend compilation of tests:

```
[INFO] --- xtend-maven-plugin:2.4.3:compile (default) @ com.reprezen.swagedit.tests ---
[ERROR] 
ERROR:  SwaggerContentAssistProcessorTest.xtend - /Users/TatianaFesenko/Documents/workspace/SwagEdit/com.reprezen.swagedit.tests/src/com/reprezen/swagedit/tests/SwaggerContentAssistProcessorTest.xtend
6: org.assertj.core.api.Assertions cannot be resolved to a type.
<...>
```

We use non-Maven dependencies in the tests by putting them into the lib folder. This approach usually works well, but not here.
Tycho is usually sensitive to the following files, I checked all of them:
- build.property file properly add teh jars to `bin.includes`
- Manifest.mf adds the jars to the `Bundle-ClassPath`

Also, I have compilation error in Eclipse, but Xtend shows me completely different errors. I thought that static imports might cause a problem, but removing them did not resolve the issue.

**Comment by tfesenko** [comment]
I noticed that during Xtend compilation Java 6 is used `Set Java Compliance Level: 1.6` and `javaSourceVersion = 1.6`. Note that we set Java 1.7 in the manifest file and preferences.

**Comment by ghillairet** [comment]
So I removed the xtend plugin from the maven build, and committed the generated Java files, it works now.

What are your errors in Eclipse?

**Comment by tfesenko** [comment]
Committing generated Java classes created a lot of noise in git. I fixed Xtend compilation by 
1) Replacing Xtend with Java in one test
2) Replacing assertions from the lib by standard JUnit assertions.
