### ISSUE TITLE
Warning instead of Error on curly braces in path item references

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#189]
Noted in [support ticket #152](https://support.reprezen.com/helpdesk/tickets/152).  

While SwagEdit disallows path item references with un-encoded curly braces, the Swagger.io editor allows them, and Swagger-UI actually _requires_ them to be un-encoded.  It won't work with URL-encoded curly braces.

Swagger-Normalizer is our immediate solution to this problem.  But users will want to be able to use un-encoded curly braces for tool portability, consistency, and readability.

Related Swagger-JS issue: https://github.com/swagger-api/swagger-js/issues/837

**Comment by ghillairet** [comment]
Possible solution in PR https://github.com/RepreZen/SwagEdit/pull/197

Previous behavior

![screen shot 2016-08-30 at 15 48 46](https://cloud.githubusercontent.com/assets/148045/18093805/7ede12b8-6ed1-11e6-9d39-207c3eb4cab3.png)

New behavior

![screen shot 2016-08-30 at 15 49 04](https://cloud.githubusercontent.com/assets/148045/18093837/97d4e7ec-6ed1-11e6-9c76-3e2a0323dea6.png)
