### ISSUE TITLE
Static validation for Swagger

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#2]

**Comment by tfesenko** [comment]
The validation is invoked on file save. Currently it's always shown at the fist symbol of the file:
<img width="269" alt="screen shot 2015-10-02 at 1 02 03 pm" src="https://cloud.githubusercontent.com/assets/644582/10252500/d4e6ad78-6905-11e5-9353-b528b863bbe1.png">

The reason is that we use Swagger validation which does not provide a line number. @ghillairet proposes to parse this error message and find the line with the error using snake-yaml.

**Comment by ghillairet** [comment]
The validator is now able to detect line numbers on these [tests](https://github.com/ModelSolv/SwagEdit/tree/develop/com.reprezen.swagedit.tests/fixtures).

Note that YAML errors are handle by YEdit (syntax errors), but semantic errors in regard to the Swagger format are handle by our validator.

**Comment by tfesenko** [comment]
It's done. For phasing and particular cases please create new issues.
