### ISSUE TITLE
Add support for templates in content assist

### ISSUE THREAD

**Issue by ghillairet** [RepreZen/KaiZen-OpenAPI-Editor#20]
The content assist popup should also provide some templates.

**Comment by ghillairet** [comment]
Support for templates has started in branch feature/20.

What's been added is a preference page where user can edit/save his own templates. 

![screen shot 2015-11-19 at 16 43 24](https://cloud.githubusercontent.com/assets/148045/11275303/5827a582-8edd-11e5-8f13-75ebe9b111fc.png)

Those templates are accessible from the content assist:

![screen shot 2015-11-19 at 16 43 42](https://cloud.githubusercontent.com/assets/148045/11275318/682f624e-8edd-11e5-90e8-6a3892f410b8.png)

**Comment by tfesenko** [comment]
1. Code templates are defined for `info`, `paths`, `definitions` and `swagger` objects. 
   For me, a code template for an individual `definition` or `path` would be helpful. Other useful code templates - `method` and `responses`.
2. Code templates are not visually recognizable from content-assist. They have a "default template" description, but it's difficult to spot. I would like to make them visually different. For example, by using different icons, font styles or colors.

**Comment by tfesenko** [comment]
Created issue #31 for additional code template.
Styling is already fixed.
