### ISSUE TITLE
Multi-File QuickOutline View

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#202]
After we fix code assist typeahead, next priority for us is multi-file support in Quick Outline View.

This should cycle through current file, project files and workspace files, the same as multi-file code assist.

To clarify the intent:  this is not about expanding references in QuickOutline view.  What we want to do is introduce top-level nodes for Swagger files, and populate the outline under each of these files.  The filter/search feature should filter across the entire outline, and this should allow fast access to any node within any swagger file in the workspace.

**Comment by ghillairet** [comment]
Preliminary implementation for this has been started in PR #225 

Screencast showing it working

![out1](https://cloud.githubusercontent.com/assets/148045/19442513/d3ddd482-9489-11e6-88ea-f09505b5f576.gif)

The content of the quick outline is being updated when the user presses the same keys used to open the quick outline (e.g. Ctrl-o).

The status of the quick outline (at the bottom of the popup) is also being updated with the following messages (where %s is replaced with the keys):
- Press '%s' to show elements only the from current file
- Press '%s' to show elements from the current project files
- Press '%s' to show elements from the current workspace files

What remain to do is fix navigation to files other than current (when user clicks on tree element) and improve performance of text filter (which hangs on large and/or multiple files).
