### ISSUE TITLE
Add additional information to content assist

### ISSUE THREAD

**Issue by ghillairet** [RepreZen/KaiZen-OpenAPI-Editor#205]
Content assist could use the description values present in the swagger schema as additional information.

Additional information are shown in a separate modal next to content assist proposals.

![screen shot 2016-09-19 at 16 55 49](https://cloud.githubusercontent.com/assets/148045/18636825/76ca2850-7e8a-11e6-9fe6-df60ad8bb28a.png)

**Comment by tedepstein** [comment]
@ghillairet , nice idea.  The screenshot makes it look like this is already done.  But I assume there is still some work remaining, or maybe this is just a mockup?

In any case, please advise as to how much effort you think this would need.

**Comment by ghillairet** [comment]
It's already in the model branch (#198), there is not much work to be done to have it finalized, only make sure all elements that have a description in their schema, have that additional information added.

**Comment by tedepstein** [comment]
> only make sure all elements that have a description in their schema, have that additional information added.

Not sure what this means.  If an element has a description in schema, shouldn't the implementation use that description dynamically?  It seems like you're saying we would need to extract that information to some other form, for presentation in the information  window.  But I would hope we can avoid that.

**Comment by ghillairet** [comment]
What I meant is that what's left to do is make sure the code that takes the description from the schema does it correctly, e.g. it does not miss any. But anyway the way it is done it should not.

**Comment by tedepstein** [comment]
OK, @ghillairet , thanks for clarifying.

**Comment by tfesenko** [comment]
Fixed in PR #210:
<img width="679" alt="screen shot 2016-10-01 at 12 38 03 pm" src="https://cloud.githubusercontent.com/assets/644582/19015536/86dbdd4e-87d4-11e6-912f-8b991d320298.png">
