### ISSUE TITLE
SwagEdit shows "Unable to Dereference URI" error on Swagger Schema

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#209]
From Slack Discussion:

> miles.daffin [9:02 AM]  
> @here I am getting an error on a project with the latest build: Description    Resource    Path    Location    Type
> unable to dereference URI "http://swagger.io/v2/schema.json#"    petstore.yaml    /Pet Store with Examples/models    line 1    Problem
> 
> Any ideas?
> Oh. I see that the URL results in 503 Service Unavailable...
> Don't know why it's gone from swagger.io. Perhaps better to source it from https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/schemas/v2.0/schema.json ??
> 
> Or perhaps from http://json.schemastore.org/swagger-2.0
> 
> andy.lowry [9:08 AM]  
> I presume it's a temporary outage of swagger.io web server
> If we changed it to something else we'd be subject to temporary outages of whatever we changed it to.
> 
> I think the best approach is to embed external artifacts needed for validation directly into swagedit. I made the suggestion a little while ago, but I haven't followed things there
> 
> reprezented [9:55 AM]  
> @here, yes, we should definitely embed our schema. In fact, SwagEdit uses its own modified version of the Swagger Schema for validation and code assist.  So I'd be interested to know where that dependency is coming from.
> 
> @miles.daffin , what was the context where you were seeing this error?
> During code generation, editing, or something else?
> 
> miles.daffin [9:57 AM]  
> uploaded an image: Pasted image at 2016-09-27, 2:57 PM 
> ![image](https://cloud.githubusercontent.com/assets/692813/18876801/0c15114a-8499-11e6-99b4-b12c11ec368e.png)
> 
> Just loaded the example project

**Comment by tedepstein** [comment]
@ghillairet and/or @tfesenko , can you please take a look ASAP? If we depend on a schema that is no longer available, this will likely affect all of our paid users and trial users.

**Comment by tfesenko** [comment]
Similar issues:
- #180 Strange error markers when machine is offline
- #113 - UnknownHostException when working offline

and also #126 - Changed lines count should not be shown in error messages

**Comment by ghillairet** [comment]
Pushed to master this fix https://github.com/RepreZen/SwagEdit/commit/caae33728dc11128e9c44fc8b35d8f8f63a917b0

That fixes the issue by making the schema anonymous and thus avoid connection to swagger server.

**Comment by tfesenko** [comment]
Confirming that the fix works.
Before the fix:
<img width="501" alt="screen shot 2016-09-27 at 10 30 59 am" src="https://cloud.githubusercontent.com/assets/644582/18878171/a843d840-849d-11e6-84fa-49c30430b62c.png">

After the fix all clean. 

Passed code review. As the change was committed directly to master, there is nothing to merge.

**Comment by tedepstein** [comment]
@ghillairet  and @tfesenko , thanks for the fast turnaround!
