### ISSUE TITLE
Code-assist: `file` as value for responses' `type`

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#215]
Code-assist suggests `file` as value for responses' `type`
<img width="391" alt="screen shot 2016-10-04 at 4 50 35 pm" src="https://cloud.githubusercontent.com/assets/644582/19092732/07b12f68-8a56-11e6-89e5-3ab883dab512.png">

I expect to see`string`, `boolean`, and other values available for request's type:
<img width="263" alt="screen shot 2016-10-04 at 5 15 51 pm" src="https://cloud.githubusercontent.com/assets/644582/19092785/507c5f92-8a56-11e6-8a33-96ba7ccec9e4.png">

Model (cursor is at `<1>`)

```
swagger: "2.0"
info:
  title: TEST API
  description: Test
  version: "1.0.0"
host: api.uber.com
schemes:
  - https
basePath: /v1
produces:
  - application/json
  - application/xml
paths:
  /products:
    get:
      summary: Product Types
      description: some desc
      parameters:
        - name: prop
          in: header
          description: Latitude component of location.
          required: true
          type: string
          format: double
      responses:
        200:
          description: foo
          schema:
            type: <1>
```

**Comment by ghillairet** [comment]
Those are different, there is only one value possible for the `type` property in a response schema, see https://github.com/RepreZen/SwagEdit/blob/master/com.reprezen.swagedit/src/com/reprezen/swagedit/schema/schema.json#L1074

**Comment by tedepstein** [comment]
@ghillairet , [Looking at the usage](https://github.com/RepreZen/SwagEdit/blob/master/com.reprezen.swagedit/src/com/reprezen/swagedit/schema/schema.json#L361) of `fileSchema` in `response`, we can see that it is `oneOf` two possible types, the other being `schema`, which has all of those other possible values for `type`.

Ideally, where there is a `oneOf` or `anyOf` construct like this, code assist should offer a union of the available values from the sub-schemas.  

Have we considered this, and are we doing this in other `oneOf` or `anyOf` cases?

**Comment by ghillairet** [comment]
Yes that's right, I overlooked this. We do union of values in that case, it does not work here because we yet don't get values from the json core schema (in that case https://github.com/RepreZen/SwagEdit/blob/master/com.reprezen.swagedit/src/com/reprezen/swagedit/schema/schema.json#L1001).

**Comment by tedepstein** [comment]
OK. We should probably fix that, as there are many places where that JSON core schema is referenced.  And should we aim to do this in a way that doesn't require an internet connection, e.g. by making these relative references to a copy of the core JSON schema that we distribute along with our specialized Swagger schema?

**Comment by ghillairet** [comment]
PR #221 fixes this issue and adds support for the core JSON schema.

![screen shot 2016-10-11 at 16 53 11](https://cloud.githubusercontent.com/assets/148045/19277772/31c5a646-8fdb-11e6-8d81-bead856ce201.png)
