### ISSUE TITLE
Code-assist for schema properties is incomplete

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#217]
There is a code template for a new `schema`, but we don't provide assintance beyond that: 
<img width="236" alt="screen shot 2016-10-04 at 5 28 58 pm" src="https://cloud.githubusercontent.com/assets/644582/19093302/936b14ae-8a58-11e6-8d3e-c597fbd95e86.png">
<img width="222" alt="screen shot 2016-10-04 at 5 29 06 pm" src="https://cloud.githubusercontent.com/assets/644582/19093303/936b5004-8a58-11e6-8e5d-0103e3fe325b.png">
<img width="339" alt="screen shot 2016-10-04 at 5 30 26 pm" src="https://cloud.githubusercontent.com/assets/644582/19093305/936d45bc-8a58-11e6-93d6-46ffbcc686e2.png">

And the reference worked:
<img width="406" alt="screen shot 2016-10-04 at 5 30 37 pm" src="https://cloud.githubusercontent.com/assets/644582/19093304/936cc52e-8a58-11e6-9084-76ce2c086459.png">

Model:

``` yaml

---
swagger: "2.0"
info:
  version: 1.0.0
  title: My API Spec
paths:
  /resourceUrl:
    get:
      responses:
        200:
          description: Success

definitions:
  Product:
    required:
      - name  
    properties:
      name:
        type: string
      description:
        type: string

```

**Comment by ghillairet** [comment]
This should work better now with changes made in PR #221

**Comment by ghillairet** [comment]
@tfesenko Should be working as expected now, should we close this?

**Comment by tfesenko** [comment]
The cases from the issue description work now
