### ISSUE TITLE
Fix performance issues with Multi-File QuickOutline View 

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#228]
Extracted from https://github.com/RepreZen/SwagEdit/pull/225#issuecomment-254605459

**Comment by tedepstein** [comment]
@tfesenko and @ghillairet , please have a look at this and plan some basic improvements.  Go for the 80% in the 80-20 rule.

**Comment by tfesenko** [comment]
Enabling "Detect periods of unresponsive UI" on `General>UI Responsiveness Monitoring` preferences page is helpful to see stacktraces of long operations. 
<img width="928" alt="screen shot 2016-10-27 at 4 51 14 pm" src="https://cloud.githubusercontent.com/assets/644582/19784977/b6caaa58-9c65-11e6-8f1b-e3df40b9f9bb.png">

**Comment by tfesenko** [comment]
Auto-expanding all elements for the project scope takes up to three seconds.
1. Here, I am opening the outline in the project scope. Its nodes are **not** expanded.
2. Then, I start filtering element by typing "q", then "w". It's slow, but below a second.
3. When I remove the last letter from my filter the Outline becomes really slow, it freezes for three seconds. After the freeze all its nodes are expanded. They should be collapsed, the same as in the step 1. 
![expand_all](https://cloud.githubusercontent.com/assets/644582/19786520/67b6e3f8-9c6c-11e6-84d2-5aa9c4578462.gif)

**Comment by tfesenko** [comment]
## `AbstractTreeViewer.expandAll()` - the ultimate fix

`treeViewer.expandAll()` is where all freezes happen according to UI Responsiveness Monitoring.
Making it fast would be an ultimate fix. I don't know if it's possible. The fix may also take too much time.

### `tree.setRedraw()` (did not help)

I tried wrapping the contents of the `modifyText()` inside a `treeViewer.getTree().setRedraw(false)`/`treeViewer.getTree().setRedraw(true)`, but it did not help. It even make it slower.

## Other optimizations

### Auto-expanding elements in project scope with a an empty filter

Auto-expanding all elements for the project scope takes up to three seconds.
1. Here, I am opening the outline in the project scope. Its nodes are **not** expanded.
2. Then, I start filtering element by typing "q", then "w". It's slow, but below a second.
3. When I remove the last letter from my filter the Outline becomes really slow, it freezes for three seconds. After the freeze all its nodes are expanded. They should be collapsed, the same as in the step 1. 
![expand_all](https://cloud.githubusercontent.com/assets/644582/19786520/67b6e3f8-9c6c-11e6-84d2-5aa9c4578462.gif)

### Keystroke delay: Refresh Outline after three symbols are typed

Ted also suggested delaying actual filtering (not doing anything) until at least three symbols are available.

## Other Quick Outline implementations

### JDT Quick Outline

JDT implementation of QuickOutline is available in `org.eclipse.jdt.internal.ui.text.JavaOutlineInformationControl`

**Comment by tedepstein** [comment]
> Ted also suggested delaying actual filtering (not doing anything) until at least three symbols are available.

That's one easy optimization.  The other is the keystroke delay:  wait until a half-second (more or less) has elapsed without a keystroke before triggering the filter logic.

**Comment by ghillairet** [comment]
I have been looking at using `org.eclipse.jface.viewers.ILazyTreeContentProvider` to implement lazy loading of the tree content, it could make things more responsive but I have not found yet how to make it work with the filter.

What I have done is make the tree collapse when the filter box is emptied.

![out1](https://cloud.githubusercontent.com/assets/148045/19862143/6c952526-9f8f-11e6-8f0a-f3772d387fc2.gif)

Will look again if the tree can be lazy loaded or use the delay strategy.

**Comment by ghillairet** [comment]
The reason why I could not get filtering working with the lazy tree is because it is simply not supported.

From [TreeViewer Javadocs](http://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjface%2Fviewers%2FTreeViewer.html)

> If the content provider is an ILazyTreeContentProvider or an ILazyTreePathContentProvider, the underlying Tree must be created using the SWT.VIRTUAL style bit, **_the tree viewer will not support sorting or filtering_**, and hash lookup must be enabled by calling StructuredViewer.setUseHashlookup(boolean).

**Comment by ghillairet** [comment]
See PR #242 

I added a timer inside the modifyListener, so that refresh happens only 500ms after the user entered text. I think that's better to do it like that than trying to count the number of letters the user entered.

For the lazy tree content provider, if we want to use it, and the timer is not enough, we could implement our own filter mechanism instead of relying on the TreeViewer filter (which in not supported for lazy content provider). That would be done by filtering the nodes tree ourselves, and use the TreeViewer.setInput() method to add those filtered nodes as the new content.

**Comment by ghillairet** [comment]
Screencast of quickoutline with the timer.

![out1](https://cloud.githubusercontent.com/assets/148045/19893680/4684e77a-a04a-11e6-965a-897acbf4d2ab.gif)

**Comment by tfesenko** [comment]
Great improvement!!
Using the same models as in https://github.com/RepreZen/SwagEdit/issues/228#issuecomment-257194385 :
![swagger_perf](https://cloud.githubusercontent.com/assets/644582/19894986/6499c28c-a025-11e6-80f8-6463be947833.gif)

**Comment by ghillairet** [comment]
Should we close this one?

**Comment by tedepstein** [comment]
I'm satisfied with the improvement in perceived performance demonstrated in the gif.  I would vote for closing this, as long as the fix has passed QA and code review.
