### ISSUE TITLE
Deprecated simple reference should display with specialized warning message

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#229]
Reported by @tedepstein in [ZEN-3016](https://modelsolv.atlassian.net/browse/ZEN-3016):

> Discovered in [support ticket #176](https://support.reprezen.com/helpdesk/tickets/176):
> We used to recognize these deprecated simple references, and provide a friendlier warning message. Now it's just giving an "invalid reference" warning, which doesn't tell the whole story.
> This is really a SwagEdit regression, apparently....

**Comment by tedepstein** [comment]
Marking high-priority, assuming it's a regression that will be relatively easy to fix.  If not, please let me know and we can discuss.

**Comment by tedepstein** [comment]
Example file attached.

[Test.zip](https://github.com/RepreZen/SwagEdit/files/544999/Test.zip)

**Comment by ghillairet** [comment]
See PR #232 

I'm not sure we supported navigation on simple reference but this PR enables it and also changes the warning message for simple refs as proposed in #203 

![out1](https://cloud.githubusercontent.com/assets/148045/19652228/54dc898a-9a10-11e6-8ab5-3c516dc8dab3.gif)
