### ISSUE TITLE
Quick Outline cycling plays alert sound

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#231]
Not certain why, but cycling through Quick Outline scopes, by repeating the hotkey combination, results in an alert or notification tone being played.  This is on Windows 10.  

Normally these sounds are reserved for error conditions or other events that the user has configured to play sounds.  Marking as "high priority" assuming it should be a simple fix.  If not, please advise, and we can discuss options.

**Comment by ghillairet** [comment]
Modified title as the sound plays also on OSX.

Not sure from where that's coming, the code for our Quick Outline is quite similar to the one for the Java Quick Outline, and that latter doesn't have this issue.
