### ISSUE TITLE
Content Assist: only show cycling prompts for reference properties

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#234]
Initially, the prompt in the content assist popup is set correctly. If you first invoke content assist in a context other than `$ref`, it shows without a prompt.

But if you invoke content assist on a reference property, and then invoke content assist on a non-reference property, it fails to reset the blank prompt.  So the same "cycling" prompt remains at the bottom:

![image](https://cloud.githubusercontent.com/assets/692813/19660743/00b948ea-99ff-11e6-9c58-7d43704e5984.png)

**Comment by ghillairet** [comment]
Fixed in PR #237
