### ISSUE TITLE
Should note that it is based on YEDit

### ISSUE THREAD

**Issue by paulvi** [RepreZen/KaiZen-OpenAPI-Editor#254]
as in https://bugs.eclipse.org/bugs/show_bug.cgi?id=491050
README  should not that it is based on YEDit https://github.com/oyse/yedit

**Comment by tedepstein** [comment]
Hi @paulvi .  Can you please clarify?  Perhaps you meant that the README "should **_note_**" that it is based on YEdit?

SwagEdit does use YEdit.  That dependency is not mentioned in the README, but it is shown in the architecture diagram on the [Development Page](https://github.com/RepreZen/SwagEdit/blob/master/DEVELOPERS_GUIDE.md#user-content-swagedit-architecture), which is referenced in the README.

**Comment by paulvi** [comment]
yes, really it was "note"

As Development page is already referenced from README, closing...
