### ISSUE TITLE
Artwork for code assist proposals

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#28]
Currently we use the standard Swagger icon for all kinds of proposals - simple and template proposals, path and definition:
<img width="636" alt="screen shot 2015-11-26 at 12 50 53 pm" src="https://cloud.githubusercontent.com/assets/644582/11428755/f81931d2-943c-11e5-8e44-89615f4c1c9c.png">

**Comment by ghillairet** [comment]
Content assist icons and text have been updated to look like this:

![screen shot 2015-11-27 at 18 08 55](https://cloud.githubusercontent.com/assets/148045/11446010/0831d15a-9532-11e5-9235-c88bfa6c1140.png)

**Comment by tedepstein** [comment]
Looks great, @ghillairet .  Nice work!

**Comment by tedepstein** [comment]
@tfesenko , I think we can close this.  Are you OK with it?
