### ISSUE TITLE
Errors on api-with-examples.yaml example

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#288]
KaiZen shows errors on the [api-with-examples.yaml](https://github.com/OAI/OpenAPI-Specification/pull/985/files#diff-a2249c9a8a8283a9fca027002f92b1e0) OpenAPI v3 example. 

Other examples from this PR are OK.

Probably it's related to the `example` definition in the JSON Schema which prohibits additional properties. Allowing them fixes three of four validation errors:
```
--- a/com.reprezen.swagedit.openapi3/src/com/reprezen/swagedit/openapi3/schema/schema_v3.json
+++ b/com.reprezen.swagedit.openapi3/src/com/reprezen/swagedit/openapi3/schema/schema_v3.json
@@ -619,7 +619,7 @@
     "example": {
       "type": "object",
       "description": "Allows sharing examples for operation requests and responses. This object can either be a freeform object, array or primitive value.  To represent examples of media types that cannot naturally represented in the OpenAPI definition, a string value can be used to contain the example with escaping where necessary.",
-      "additionalProperties": false
+      "additionalProperties": true
     },
     "links": {
       "type": "object",
```

-----------
Problem markers:
```
Description	Resource	Path	Location	Type
Failed to match exactly one schema:
 - /definitions/responseOrReference/oneOf/0:
	Failed to match exactly one schema:
	 - /definitions/exampleOrReference/oneOf/0:
		 - object has properties "version" which are not allowed
	 - /definitions/exampleOrReference/oneOf/1:
		 - object has properties "version" which are not allowed
		 - object has missing required properties "$ref"
 - /definitions/responseOrReference/oneOf/1:
	 - object has missing required properties "$ref"
	 - object has properties "content", "description" which are not allowed
	api-with-examples.yaml	/Foo	line 126	Problem
Failed to match exactly one schema:
 - /definitions/responseOrReference/oneOf/0:
	Failed to match exactly one schema:
	 - /definitions/exampleOrReference/oneOf/0:
		 - object has properties "version" which are not allowed
	 - /definitions/exampleOrReference/oneOf/1:
		 - object has properties "version" which are not allowed
		 - object has missing required properties "$ref"
 - /definitions/responseOrReference/oneOf/1:
	 - object has properties "content", "description" which are not allowed
	 - object has missing required properties "$ref"
	api-with-examples.yaml	/Foo	line 82	Problem
Failed to match exactly one schema:
 - /definitions/responseOrReference/oneOf/0:
	Failed to match exactly one schema:
	 - /definitions/exampleOrReference/oneOf/0:
		 - object has properties "versions" which are not allowed
	 - /definitions/exampleOrReference/oneOf/1:
		 - object has properties "versions" which are not allowed
		 - object has missing required properties "$ref"
 - /definitions/responseOrReference/oneOf/1:
	 - object has missing required properties "$ref"
	 - object has properties "content", "description" which are not allowed
	api-with-examples.yaml	/Foo	line 12	Problem
Failed to match exactly one schema:
 - /definitions/responseOrReference/oneOf/0:
	Failed to match exactly one schema:
	 - /definitions/exampleOrReference/oneOf/0:
		 - value of type string is not allowed, value should be of type object
	 - /definitions/exampleOrReference/oneOf/1:
		 - value of type string is not allowed, value should be of type object
 - /definitions/responseOrReference/oneOf/1:
	 - object has missing required properties "$ref"
	 - object has properties "content", "description" which are not allowed
	api-with-examples.yaml	/Foo	line 44	Problem

```

**Comment by tedepstein** [comment]
@tfesenko , about this:

> Probably it's related to the example definition in the JSON Schema which prohibits additional properties. Allowing them fixes three of four validation errors:

Have we raised this issue on the OpenAPI spec project?  We should get a clear answer as to whether the examples are wrong, or the OpenAPI 3 spec needs to be updated.

**Comment by tfesenko** [comment]
Related to #292 "JSON Schema for OpenAPI v3"

**Comment by tfesenko** [comment]
The schema seems to be right, and the spec example from the PR should be corrected. `additionalProperties` should be left prohibited for the `examples`, just like for all other elements.

So, what's wrong with `api-with-examples.yaml`?
* Map vs List
Examples for a response [should be](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#media-type-object) a `Map[ string, Example Object | Reference Object]`, but in `api-with-examples.yaml`, they are a **list** of example values. 
* `value`/`externalValue` vs inlining directly
The example value [should be stored](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#example-object) in the `value` property for inline examples, and in the `externalValue ` property for externally defined examples. `api-with-examples.yaml` defines the values directly under the `examples` element, instead of using `value` or `externalValue`. 

Based on t[his comment](https://github.com/OAI/OpenAPI-Specification/pull/985#issuecomment-297882773), they are aware of this problem: 
> examples need to be updated to the new construct.

So, we should wait for updated v3 example and should not worry about validation errors in `api-with-examples.yaml` for now.

**Comment by tfesenko** [comment]
Fixed in https://github.com/OAI/OpenAPI-Specification/pull/1286
Our `api-with-examples.yaml` was updated accordingly, an automated test verifies that this spec can be loaded without validation errors.
