### ISSUE TITLE
Open API v3: Content Assist for References

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#289]
https://modelsolv.atlassian.net/browse/ZEN-3442

In OpenAPI 3, all of these are supported as reusable components, each with its own designated subsection within the OpenAPI Components object:

- [x] Schema Definitions
- [x] Parameters
- [x] Responses
- [x] Path Items
- [ ] Produces/Consumes (does not exist in v3)
- [x] Links - used in responses
- [x] Examples
- [x] Request Bodies
- [x] Headers - used in Link and Response
- [x] Callbacks - used in Operation
- [ ] Security Schemes (see #304)

## Tests
- [x] Parameter,
- [x] Path item,
- [x] Callback,
- [x] Header,
- [x] Example,
- [x] Link,
- [x] Request Bodies
- [ ] Schema Definitions
- [ ] Responses

We already provided support for references to `Schema Definitions` and `Path Items`, but other components need their own `ContextTypes`, see `com.reprezen.swagedit.openapi3.assist.OpenApi3ReferenceProposalProvider`.

**Comment by ghillairet** [comment]
@tfesenko I added support for parameters, responses, requestBodies and links.

You can try with these components

```yaml
components:
  links:
    UserCommitHistory:
      operationId: userCommitHistory
      parameters:
        username: $response.body#/user/username
        page: 0
    
  requestBodies:
    rq:
      description: user to add to the system
      content: 
        'application/json':
          schema:
            $ref: '#/components/schemas/User'
          examples:
            user:
              summary: User Example
              externalValue: 'http://foo.bar/examples/user-example.json'
  responses:
    '200':
      description: Ok
  parameters:
    petId:
      name: petId 
      in: path
      required: true
      description: The id of the pet to retrieve
      schema:
        type: string
```

Parameter reference

```yaml
/pets/{petId}:
  get:
    summary: Info for a specific pet      
    parameters:
      - $ref: "#/components/parameters/petId"
```

Response reference

```yaml
/pets/{petId}:
  get:
    responses:
      200:
        $ref: "#/components/responses/200"
```

Request Body reference

```yaml
post:
  summary: Create
  description: Create a new item
   requestBody: 
     $ref: "#/components/requestBodies/rq"
```

Link reference

```yaml
responses:
  300:
    description: error
    links:
      myLink:
        $ref: "#/components/links/UserCommitHistory"
```

**Comment by tedepstein** [comment]
related issue: #324
