### ISSUE TITLE
OpenAPI v3: Content Assist Code Templates

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#290]
https://modelsolv.atlassian.net/browse/ZEN-3443

We expect to create a new set of default code templates for OpenAPI v3. The code templates are provided based on the code template contexts, so we will need to 
1. properly calculate contexts and 
2. create new contexts for the new elements.

We will also need a preferences page for code templates (see https://modelsolv.atlassian.net/browse/ZEN-3448)

See the `com.reprezen.swagedit.templates` as an example how it's implemented for Swagger v2

**Comment by tedepstein** [comment]
@tfesenko , AFAIK, this is essentially complete; we should just have separate open issues for any contexts that need templates to be added, improved, or that are not showing their templates as expected.
