### ISSUE TITLE
OpenAPI v3 Validation: fix messages for `oneOf` cases

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#291]
Currently validation message for a `oneOf` case looks like this:
<img width="473" alt="screen shot 2017-05-09 at 5 20 02 pm" src="https://cloud.githubusercontent.com/assets/644582/25873289/efa4480c-34db-11e7-9516-96f2205df9c8.png">

We addressed it for Swagger v2 by introducing a `title` property to JSON Schema. 
`com.reprezen.swagedit.core.validation.SwaggerError.MultipleSwaggerError.getHumanFriendlyText(JsonNode, String)` reads the `title` property i it's available, implemented as a part of https://github.com/RepreZen/KaiZen-OpenAPI-Editor/issues/9 and https://github.com/RepreZen/KaiZen-OpenAPI-Editor/pull/108

**Comment by tfesenko** [comment]
Related to #292 "JSON Schema for OpenAPI v3"

**Comment by tedepstein** [comment]
@tfesenko , is it possible for the gnostic schema generator to scrape an appropriate `title` from the OAS specification markdown?  If not, how do you propose to maintain titles in a way that won't be clobbered by regeneration?

**Comment by tfesenko** [comment]
@tedepstein asked:
> is it possible for the gnostic schema generator to scrape an appropriate title from the OAS specification markdown? 

We don't need it now (extracted to #296). In most cases, validation can get enough information from JSON Schema in its current state. I implemented it in PR #108 but forgot to properly migrate the code...
