### ISSUE TITLE
JSON Schema for OpenAPI v3

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#292]
We use a modification of the JSON Schema provided by [googleapis/gnostic](https://github.com/googleapis/gnostic). We use the [SwagEdit branch](https://github.com/RepreZen/gnostic/tree/SwagEdit) to generate our JSON Schema. Thanks to @timburks and @MikeRalphson for the contribution!

**Comment by tedepstein** [comment]
@tfesenko , @ghillairet , I think we can close this one, right?
