### ISSUE TITLE
OpenAPI v3: Content Assist for parameter.in should show allowed values

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#298]
Currently, it only shows that it's a string:
<img width="182" alt="screen shot 2017-05-16 at 3 11 24 pm" src="https://cloud.githubusercontent.com/assets/644582/26123753/03a01a20-3a4a-11e7-9b6e-a4514d803c3a.png">

See #299 for more info

**Comment by ghillairet** [comment]
This was done in https://github.com/RepreZen/KaiZen-OpenAPI-Editor/pull/376
