### ISSUE TITLE
OpenAPI v3: Validation should show a warning for disallowed values in parameter.in

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#299]
Related to #298
Specification allows only [four values](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#parameterObject):
> Possible values are "query", "header", "path" or "cookie".

JSON Schema for v2 provides enum values for each specific subschema:
```json
    "queryParameterSubSchema": { <...>
        "in": {
          "type": "string",
          "description": "Determines the location of the parameter.",
          "enum": [
            "query"
          ]
        },
```
JSON Schema for v3 is very simple and does not provide any constraints:
```json
    "parameter": { <...>
        "in": {
          "type": "string"
        },
```

**Comment by ghillairet** [comment]
Done in #376 I think.

![screen shot 2017-09-22 at 14 30 44](https://user-images.githubusercontent.com/148045/30744516-ad270adc-9fa2-11e7-80ac-417b6dd41ef4.png)

**Comment by tedepstein** [comment]
Thanks @ghillairet .  BTW, is there any way to turn off the "changed line" notifications that appear in these markers?  They seem to just be adding noise.

**Comment by ghillairet** [comment]
@tedepstein Not sure how. I also don't know why it is there, it is not always present and I have trouble reproducing it. For example below it is not show.

![paths](https://user-images.githubusercontent.com/148045/30744743-cd131560-9fa3-11e7-86a3-7b38d0c9a3cb.gif)

**Comment by tedepstein** [comment]
@ghillairet , OK, I would not say it's critical, but I will open a separate issue for it, and at some point maybe we can take a closer look.

**Comment by tedepstein** [comment]
Issue #126 already captures this.

**Comment by ghillairet** [comment]
@tfesenko I think we can close this one.
