### ISSUE TITLE
Live validation for Swagger Editor

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#3]

**Comment by tedepstein** [comment]
@tfesenko , can you please clarify?

**Comment by tfesenko** [comment]
I meant "Live validation". It's implemented. 
Batch validation is performed on file save. Done in #2 Static validation for Swagger 

See https://wiki.eclipse.org/BPMN2-Modeler/DeveloperTutorials/Validation#Live_vs_Batch_Validation
