### ISSUE TITLE
Tests for OpenAPI v3 editor

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#301]
Issue placeholder. Details to be defined later.

We have tests for Swagger v2 editor in `com.reprezen.swagedit.tests`, it tests `com.reprezen.swagedit` and `com.reprezen.swagedit.core` plugins.

Create tests for OpenAPI v3 editor. Define what kind of tests we need. Code-assist? Validation? Contexts for code templates?

Should we split  `com.reprezen.swagedit.tests` into parts?

**Comment by tfesenko** [comment]
Added a plugin for OpenAPI v3 tests in 	edfa183

**Comment by tedepstein** [comment]
Adding to current sprint.  Leaving it to @tfesenko  and @ghillairet to determine an appropriate level of test coverage for this sprint. The goal of the sprint is to have complete editing support for OpenAPI 3.0, including all obvious validations and code assist contexts.

**Comment by tfesenko** [comment]
I think we have a good test coverage for OAS3. Closing this issue, we can always create more specific issues later.
