### ISSUE TITLE
OpenAPI v3: code assist for security scheme in security requirement

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#304]
Extracted from #289

Security Schemes are used by Security Requirement Object which
references them by the [name, not by JSON Pointer](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#security-requirement-object):
> Each name MUST correspond to a security scheme which is declared in the Security Schemes under the Components Object. If the security scheme is of type "oauth2" or "openIdConnect", then the value is a list of scope names required for the execution. For other security scheme types, the array MUST be empty.

**Comment by ghillairet** [comment]
@tfesenko Can be close. 

Content assist for security scheme has been merged in #332. 

What doesn't work is navigation to security scheme component, this should be fixed in a separate issue. (see https://github.com/RepreZen/KaiZen-OpenAPI-Editor/issues/335)
