### ISSUE TITLE
OpenAPI v3: Validation for Link#operationRef values

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#306]
Related to #305 

[Link#operationRef](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#link-object) is
> a relative or absolute reference to an OAS operation. This field is mutually exclusive with the operationId field, and must point to the fragment of a valid OAS definition.

Validate if referenced value exists and it's an operation.

**Comment by ghillairet** [comment]
@tfesenko Validation works when operationRef is a local reference but fails when it's an external one (absolute ref).

**Comment by ghillairet** [comment]
I would do it once #358 is merged since it is likely to reuse code from it.

**Comment by ghillairet** [comment]
See PR #414
