### ISSUE TITLE
OpenAPI v3: Code assist for Link#operationId

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#307]
Extracted from #289 
[Link#operationId](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#link-object) is
> the name of an existing, resolvable OAS operation, as defined with a unique operationId. This field is mutually exclusive with the operationRef field. Relative operationRef values MAY be used to locate an existing Operation Object in the OAS.

Show operationIds from the current model

To clarify: can we reference operationIds from external models?
Answer: No, only local elements.
>  In the case of an operationId, it MUST be unique and resolved in the scope of the OAS document

**Comment by ghillairet** [comment]
@tfesenko Can be close

Merged in #332 

Provides content assist for local operationIds, specs does not mention that it should work for external operations (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#fixed-fields-17)

![screen shot 2017-09-27 at 18 13 36](https://user-images.githubusercontent.com/148045/30924663-b527475e-a3af-11e7-8eac-b2f83e3558da.png)

Remaining issues
- Navigation does not work (see #335 )
