### ISSUE TITLE
OpenAPI v3: Validation for the value of Link#operationId

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#308]
Related to #307 

[Link#operationId](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#link-object) is
> the name of an existing, resolvable OAS operation, as defined with a unique operationId. This field is mutually exclusive with the operationRef field. Relative operationRef values MAY be used to locate an existing Operation Object in the OAS.

Validation should verify that an operation with operationIds exists.

To clarify: can we reference operationIds from external models? 
Answer: No, only local elements.
>  In the case of an operationId, it MUST be unique and resolved in the scope of the OAS document

**Comment by ghillairet** [comment]
@tfesenko I think this one can be closed.

Behaviour seen on master

![sc](https://user-images.githubusercontent.com/148045/30963329-577dbc5c-a44d-11e7-9acf-8dd4195db07b.gif)

**Comment by tfesenko** [comment]
@ghillairet , thanks!
I can see a validation error too. The current error message is `Invalid object reference, the referenced object is not of expected type`, it can be improved and provide information that an operation with this operationId does not exist at all. 

<img width="515" alt="screen shot 2017-09-28 at 9 05 59 am" src="https://user-images.githubusercontent.com/644582/30968143-54085f6c-a42c-11e7-8429-b0f42db9f8ae.png">
