### ISSUE TITLE
OpenAPI v3: code assist for the values of `type`

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#313]
Code-assist for the schema type only shows that the value should be a string value:
<img width="240" alt="screen shot 2017-05-22 at 3 23 25 pm" src="https://cloud.githubusercontent.com/assets/644582/26324940/e0d4aaac-3f02-11e7-88d2-1df2d55fe9f6.png">

Code assist for v2 shows a list of types:
<img width="264" alt="screen shot 2017-05-22 at 3 23 39 pm" src="https://cloud.githubusercontent.com/assets/644582/26324961/fd22cd06-3f02-11e7-9c77-23a87cbddbe9.png">

**Comment by ghillairet** [comment]
In v2, the property `type` in schema definition is defined as this

```json
"type": {
  "$ref": "http://json-schema.org/draft-04/schema#/properties/type"
},
```

That reference points to an anyOf definition

```json
"type": {
   "anyOf": [
     { "$ref": "#/definitions/simpleTypes" },
     {
       "type": "array",
       "items": { "$ref": "#/definitions/simpleTypes" },
       "minItems": 1,
       "uniqueItems": true
      }
    ]
}
```

While in v3, the type property is simply defined as a string

```json
"type": {
  "type": "string"
}
```
