### ISSUE TITLE
Code template for callbacks in operation

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#321]
Related to #320 
We should provide a code template for callbacks inside operations:
<img width="417" alt="screen shot 2017-05-24 at 10 14 53 am" src="https://cloud.githubusercontent.com/assets/644582/26407865/45e45380-406a-11e7-923b-33d29ff7b87a.png">

**Comment by ghillairet** [comment]
I updated the templates to use the same callback templates in both operations and components.

See PR #331

![callbacks](https://cloud.githubusercontent.com/assets/148045/26489335/44ef19f8-4207-11e7-89a4-eb02277f6dc5.gif)
