### ISSUE TITLE
Typeahead doesn't work on code assist for keywords / property names

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#322]
Originally reported as:

> It only seems to work in `$ref` property value context, not in a context that is expecting a defined property name.  When I invoke content assist and start typing, the suggestion window disappears. Did we never implement typeahead for property names, or is this a more specific problem?

This is wrong.  But there are some contexts where attempt to type ahead will make the suggestion list disappear immediately.  From what I can tell so far, it doesn't work after an indented array like this:

![image](https://cloud.githubusercontent.com/assets/692813/26424150/37299934-409e-11e7-8a97-907c84ff9d3b.png)

Here, I'm trying to insert a `callbacks` property. When I type the letter 'c', the suggestion list disappears. It seems to happen whenever the preceding content is an array, like the one shown, but seems to work otherwise. 

See `beamup_path_estimates_time.yaml` in the attached zip file:
[Multi-file BeamUp API (OAS3).zip](https://github.com/RepreZen/KaiZen-OpenAPI-Editor/files/1027187/Multi-file.BeamUp.API.OAS3.zip)

**Comment by tedepstein** [comment]
Another example here:

![image](https://user-images.githubusercontent.com/692813/28842309-22853f7a-76cb-11e7-95fe-0052603333ec.png)

Example file attached.  

[callback-example.zip](https://github.com/RepreZen/KaiZen-OpenAPI-Editor/files/1191643/callback-example.zip)

Where you see the 'de', that was my attempt to find 'description' in the keyword suggestion list. Typing those letters caused the suggestion window to disappear immediately.

**Comment by tedepstein** [comment]
@tfesenko , I don't know for certain whether this issue is specific to OpenAPI v3, but I applied the label anyway.  I have only seen it in the OAS3 editor. If I knew a specific set of conditions that makes it happen, I could try testing against Swagger-OpenAPI v2. But it's probably more efficient to diagnose it on your side, and then determine whether the problem could also affect v2.

**Comment by tedepstein** [comment]
@tfesenko , does PR #368 address this?  That PR says it's a fix for OAS 3 keywords.  In yesterday's comment, I showed the problem happening on "description", which is in OAS v2 and v3. So I'm not sure where the boundaries of the problem and the solution are. 

And BTW, PR 368 did not mention this issue #322.

**Comment by tedepstein** [comment]
Marked this one as `Pending Confirmation`.  We should see if was fixed in PR #368.

**Comment by tfesenko** [comment]
Fixed in PR #368:
<img width="324" alt="screen shot 2017-09-15 at 12 28 25 pm" src="https://user-images.githubusercontent.com/644582/30478556-d2e26230-9a11-11e7-8c5a-1329f6669e7f.png">
<img width="357" alt="screen shot 2017-09-15 at 12 30 28 pm" src="https://user-images.githubusercontent.com/644582/30478557-d2e5d21c-9a11-11e7-80c2-0cbb077b8d5c.png">
