### ISSUE TITLE
OAS3: Validation of $ref property values should show error on unexpected object type

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#323]
Validation seems happy as long as it can resolve each `$ref` property to a valid JSON or YAML object.  It should validate that the referenced object is of the expected type, meaning that it conforms to the JSON schema that can be used in place of the $ref.

**Comment by tfesenko** [comment]
Often times (always?), JSON Schema provides needed information for references as references are defined inside an `xyzOrReference` element:
```json
"schemas": {
          "$ref": "#/definitions/schemasOrReferences"
        }
```

**Comment by ghillairet** [comment]
See PR #342 

Error is now shown when reference is not of expected type. (I haven't tested yet on all possible kind of references). Also doesn't work yet for references that are not in a $ref property.

![validation](https://cloud.githubusercontent.com/assets/148045/26635747/0ffcab58-461b-11e7-81e4-8c646c0557a6.gif)

**Comment by tfesenko** [comment]
As discussed at today's SUM, this issue only covers the `$ref` references, it does NOT cover securityScheme, operationRef and operationId. The focus is on OpenAPI v3, and support for v2 is optional, we just should not break it :) 

Another topic that we discussed at today's SUM is more tests. We need to check for
* No false negatives: a valid model should not be marked as invalid (see my comment about schema arrays)
* No false positives: invalid models should not be marked as valid.

How can we test it all? 
## $ref usages
`$ref` references can substitute the following elements:
Components which are usually described with the "xyzOrReference":
 * Schema Definitions
 * Parameters
 * Responses
 * Links
 * Examples
 * Request Bodies
 * Headers
 * Callbacks
 * Responses

PLUS

* Path Items, where the `$ref` is described along with the other properties:
 ```json
        "$ref": {
          "type": "string"
        },
        "summary": {
          "type": "string"
        },
```

OpenAPI v3 also allows references to `example` (singular), which is a freeform example. It's different from the `examples` object which also provides the name and/or description.

Each of these 10 elements can be referenced in different contexts. I created OpenAPI v3 specs demonstrating all major use cases for reference in com.reprezen.swagedit.openapi3.tests/resources/code-assist/references .  Schema ref example has too many new cases, e.g. for `oneOf`, `not`, or `anyOf` and is under development. I will also create an example for responses references. 

### False negatives
All these examples should be considered valid by our validator. Tests from PR #329 should do the job. @ghillairet , can you please confirm that these tests actually use the new `checkReferenceType()` check? 

### False positives
We should test that references to invalid elements create validation errors (or, warnings?). We started it in `#testValidationShouldFail_IfRefIsNotCorrectType()`. 
Ideally, we would want to take all allowed contexts for references (see resources/code-assist/references/), and for each of them try all possible invalid values, then make sure that we are getting validation errors. We should try at least one invalid reference for each context. 

#### Validation message
I suggested providing the valid type in the error message. Tests for the message are recommended, but that don't need to be very thorough. 

We should do it for component objects and for path items.

## Action items
@tfesenko to provide spec examples for references to schema and responses
@ghillairet to finish implementation and add tests

**Comment by tedepstein** [comment]
@tfesenko , this looks good.  A couple of comments:

> As discussed at today's SUM, this issue only covers the $ref references, it does NOT cover securityScheme, operationRef and operationId. 

IIRC, `securityScheme` and `operationId` are simple name references, not JSON References.  But `operationRef` follows JSON Reference syntax, just like a `$ref` property.  Is that correct?  In that case, we want to make sure it has the same validation behaviors as `$ref` properties. If you're not covering that requirement in the scope of this issue, please open another one for that.

> The focus is on OpenAPI v3, and support for v2 is optional, we just should not break it :)

OK, but again, if we're not covering v2 here, we should open a separate issue for it.  We want v2 validations to work the same way.

**Comment by ghillairet** [comment]
I fixed the issue with arrays and added tests for both v3 and v2, I'm not sure it works on all cases. I haven't added the required type in the message, not sure it will be meaningful, often the type is a complex type (anyOf, oneOf, etc..) that may not be so clear to the user. Also what should be added in the message, the pointer to the type?

**Comment by tfesenko** [comment]
Thanks, @ghillairet ! I will have a look at it today.

>  I haven't added the required type in the message, not sure it will be meaningful, often the type is a complex type (anyOf, oneOf, etc..) that may not be so clear to the user. Also what should be added in the message, the pointer to the type?

Anything that could give a hint of what is actually expected. We can experiment with different messages next week.

**Comment by tfesenko** [comment]
Extracted #345 "Validation of *remote* $ref property values should show error on unexpected object type". We can address it later.
However, invalid remote $refs should never break the validation, we should be aware of it in the scope of this issue (#323)

**Comment by tfesenko** [comment]
@tedepstein wrote:
> If you're not covering that requirement in the scope of this issue, please open another one for that.

We already had
#308 OpenAPI v3: Validation for the value of Link#operationId OpenAPIv3
#306 OpenAPI v3: Validation for Link#operationRef values OpenAPIv3
I created #347 OpenAPI v3: validation for SecurityRequirement#{securitySchemeName} 

> OK, but again, if we're not covering v2 here, we should open a separate issue for it. 

Created
#346 Swagger v2: Validation of $ref property values should show error on unexpected object type

**Comment by tfesenko** [comment]
Current state:

- [x] Local references are validated, wrong values cause a validation error
- [x] External and remote references are not type-checked (#353, #345)
- [ ] We are still working on the phrasing (#354)

## Inconsistent severity
The way how we assign severity for reference values seems very inconsistent:
* Invalid JSON Pointer: **warning**
* Valid JSON Pointer, but the element does not exist: **warning**
* Unexpected type:
  * Current file: **error**
  * External file: **nothing**
  * Remote file: **nothing**

- [x] I think we should change the severity of unexpected type in a local file to a warning.
I will do it before merging the PR.

**Comment by ghillairet** [comment]
See PR https://github.com/RepreZen/KaiZen-OpenAPI-Editor/pull/358 for validation of external references types.

**Comment by tedepstein** [comment]
@tfesenko , I think we need to update the status of this issue.  There's a checklist in your comment above.  Some of the still-unchecked items in that checklist look like they are now complete.  And there are some comments indicating other work to be done, or decisions to be made, but there are no checkboxes for those.  Please review and update.

**Comment by tfesenko** [comment]
Only remaining sub-issue is #354 "Better validation message for unexpected object type for $ref properties #354", other sub-issues are closed.
Closing this issue.
