### ISSUE TITLE
Missing code assist contexts in callbacks

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#324]
Some of this might have been fixed since the API Studio 1.5.11.7024 build I've been testing with.  

I put together a callback definition, and found that content assist didn't work correctly in the following contexts:

![image](https://cloud.githubusercontent.com/assets/692813/26425159/dae11450-40a1-11e7-8739-e8dd0ccd8fb3.png)

1. Missing `objectResource` template.
2. Missing operation templates for `get`, `post`, etc.
3. Missing media types list.  (This is a broader problem in OAS3, since they have several property names that are supposed to be media type names.  I'll open a separate issue for this.)
4. Missing schema template(s)
5. Missing type enum in content assist (already noted elsewhere) and validation.  Any string value is accepted by the validator.
6. Missing format content assist. (Also considers any string value to be valid, but this is correct with respect to the OpenAPI spec.
7. Missing response templates.

I'd suggest creating a new issue for each of the new and changed sections of the OAS spec, and working through each one to make sure they are covered in our contexts for code templates, specialized content assist, and specialized validation.

**Comment by tfesenko** [comment]
@tedepstein , the contexts were not included to the issue, can you please add them?

**Comment by tedepstein** [comment]
@tfesenko , contexts are specified. I think our comments may have just crossed paths when I first entered this a couple of months ago. Can you confirm that my description of contexts is good enough ?

**Comment by tedepstein** [comment]
just re-tested this.  Issues 4, 5 & 6 as annotated above seem to be resolved.  The other issues remain.

**Comment by tfesenko** [comment]
See https://github.com/RepreZen/KaiZen-OpenAPI-Editor/pull/392
