### ISSUE TITLE
 Navigation to Operation#securityScheme, Link#operationId, and Link#operationRef

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#335]
PR #332 provided code assist for Operation#securityScheme, Link#operationId, and Link#operationRef, which is a variation of reference. We can't navigate to references elements now, but it would be good to add navigation.
We have a similar case in v2 with navigation to the schema definitions via the simple names (`com.reprezen.swagedit.editor.hyperlinks.DefinitionHyperlinkDetector`). 

It's a "nice to have" feature, we don't have to do it immediately.

**Comment by tedepstein** [comment]
To clarify my understanding of this:  Hyperlink navigation through [Reference Objects](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#referenceObject) generally works in KZOE, with 2.0 and 3.0 specifications. 

What doesn't work is navigation through some of the "reference-like" constructs that are not really Reference Objects.  @tfesenko , is this correct?

Based on this understanding, I'm not including this issue in the current sprint (via the "Current Sprint" label in GitHub issues).  We'll save it for next sprint.

**Comment by tfesenko** [comment]
@tedepstein wrote:
> Hyperlink navigation through Reference Objects generally works in KZOE, with 2.0 and 3.0 specifications.

This is correct, `JsonReferenceHyperlinkDetector` takes care of it.
> What doesn't work is navigation through some of the "reference-like" constructs that are not really Reference Objects

Yes. But it's not hard to make navigation work for other "reference-like", e.g. `PathParamHyperlinkDetector` provides navigation from URL to path parameters.

**Comment by tedepstein** [comment]
OK, @tfesenko , moving to current sprint.  Thanks for that clarification.

**Comment by ghillairet** [comment]
See PR #406 

In action:


![media2](https://user-images.githubusercontent.com/148045/31233381-d68d3cbc-a9ec-11e7-95bd-50a89bdf286b.gif)
