### ISSUE TITLE
OpenAPI v3: validation for SecurityRequirement#{securitySchemeName}

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#347]
Extracted from #323 

See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#patterned-fields-3:
> Each name MUST correspond to a security scheme which is declared in the Security Schemes under the Components Object. If the security scheme is of type "oauth2" or "openIdConnect", then the value is a list of scope names required for the execution. For other security scheme types, the array MUST be empty.

**Comment by ghillairet** [comment]
Done in PR #405 

Validation of oauth and OpenIdConnect schemes

![media](https://user-images.githubusercontent.com/148045/31229667-cbb8db3a-a9e1-11e7-8a66-f7b62cc66a07.gif)

Validation of other schemes (should be only empty arrays)

![media2](https://user-images.githubusercontent.com/148045/31229680-d613be1a-a9e1-11e7-8499-f55cf7f78f6a.gif)
