### ISSUE TITLE
Remove "experimental" qualifier from File > New entry for OpenAPI 3

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#349]
We currently have "OpenAPI v3 Spec (experimental)" in the *File > New* wizard.  

![image](https://cloud.githubusercontent.com/assets/692813/26762024/8bd400ba-4908-11e7-893e-16e1f1b7a984.png)

As soon as we have reached a reasonable level of test coverage, we should remove the "(experimental)" qualifier.

**Comment by tedepstein** [comment]
@tfesenko , @ghillairet , it's time to remove this.

**Comment by tedepstein** [comment]
@ghillairet , this is an easy one that we should do now, before our next release.

**Comment by ghillairet** [comment]
@tedepstein This one has been merged already. I am closing it.

Wizard from master:

![screen shot 2017-08-30 at 14 53 01](https://user-images.githubusercontent.com/148045/29873293-1a980796-8d93-11e7-8d62-7df629424151.png)
