### ISSUE TITLE
Hyperlink navigation doesn't work schema $ref nested in callback

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#365]
In the Callback example, there's a nested reference to a schema:

![image](https://user-images.githubusercontent.com/692813/28841161-4b4d06da-76c7-11e7-812b-f1c3c5bf2af1.png)

The referenced schema object does not exist.  The JSON Reference is therefore invalid, but it's not marked with a validation error as it should be.  Maybe refs aren't being validated at all in OpenAPI v3 yet?

**Comment by tedepstein** [comment]
This is a red herring.  The real problem is that the type `UserLogData` is not defined.  It's an invalid reference, not marked with an error.

**Comment by ghillairet** [comment]
@tedepstein When I open that example I see a warning next to this $ref.

![screen shot 2017-08-16 at 15 56 43](https://user-images.githubusercontent.com/148045/29366946-a2de7606-829b-11e7-9cd5-2940b3e42d5f.png)

**Comment by tfesenko** [comment]
I am seeing a warning too:
<img width="834" alt="screen shot 2017-09-20 at 3 55 10 pm" src="https://user-images.githubusercontent.com/644582/30647603-29c28ce8-9e1c-11e7-8e3c-144be07713e6.png">
