### ISSUE TITLE
Content assist on format property doesn't work 

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#366]
I don't get any usable code assist here:

![image](https://user-images.githubusercontent.com/692813/28842023-1695d90a-76ca-11e7-825e-c2fdb184f096.png)

**Comment by ghillairet** [comment]
The `format` property has only a type of string, should we add some default values for content assist?

**Comment by tedepstein** [comment]
I believe it's similar to Swagger 2.0 - Any string value is acceptable, but there are also some pre-defined values that we should offer in content assist.  You'll need to check the OAS 3.0 specification to see what the pre-defined values are, as they may have changed from 2.0.

**Comment by ghillairet** [comment]
See PR #369 

I used the values from the [spec](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.0.md#dataTypeFormat) to create the content assist proposals. It also reacts on if a value is present in the object `type` property. So it shows only values that are applicable to the current type (as defined in the spec).

![format](https://user-images.githubusercontent.com/148045/28923871-d4f6fbc2-785f-11e7-879f-2c392a88d210.gif)

**Comment by tedepstein** [comment]
@ghillairet very nice!  Thanks.
