### ISSUE TITLE
Navigation from path parameters is broken in v3

### ISSUE THREAD

**Issue by ghillairet** [RepreZen/KaiZen-OpenAPI-Editor#379]
Clicking on a path parameter does not make the cursor move to the parameter definitions like it does in v2.
For example, in the petstore.yaml example, clicking on `petId` in `/pets/{petId}` from line 54 navigates to the path parameter

**Comment by tedepstein** [comment]
Possibly related to #365?

**Comment by ghillairet** [comment]
@tedepstein No it's not related. The hyperlink detectors for parameters was simply not present in OpenAPI v3 editor. I added it in PR #380
