### ISSUE TITLE
OpenAPI v3: Content assist for media types

### ISSUE THREAD

**Issue by ghillairet** [RepreZen/KaiZen-OpenAPI-Editor#395]
Similar to what has been done in https://github.com/RepreZen/KaiZen-OpenAPI-Editor/issues/196 for v2, content assist for media types can be provided for request body content types.

**Comment by tfesenko** [comment]
Extracted from #324

**Comment by ghillairet** [comment]
Done in #404 

![media](https://user-images.githubusercontent.com/148045/31181695-438f8868-a922-11e7-8be5-2ac7fb0888b4.gif)
