### ISSUE TITLE
Swagger v2: code assist for response code creates invalid value 

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#399]
PR #396 "OpenAPI v3: code assist for response code creates invalid value" implemented intelligent code-assist for response code for OAS3. Provide the same functionality for Swagger 2.

Note: Have a look at `ResponseCodeContentAssistExt`, probably simply changing the `pointer` would do the trick.

**Comment by ghillairet** [comment]
Can you confirm it is not working for you for v2? I have it working for me.

![screen shot 2017-10-04 at 16 15 19](https://user-images.githubusercontent.com/148045/31180635-688ea5de-a91f-11e7-90f6-8c1f4ec13f99.png)

**Comment by tfesenko** [comment]
Hmm, it works for me now:
<img width="772" alt="screen shot 2017-10-04 at 3 10 12 pm" src="https://user-images.githubusercontent.com/644582/31194769-2e972256-a916-11e7-9925-fe6796482991.png">

Closing
