### ISSUE TITLE
Code assist on `in` key immediately selects "body", doesn't show other options

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#42]
I expected code assist to offer any legal value for in `in` keyword:  body, query, etc., as defined in the Swagger 2.0 specification.  But it just immediately inserted "body" as shown here:

```
paths:
  /products:
    get:
      summary: Product Types
      description: |
        The Products endpoint returns information about the *Uber* products
        offered at a given location. The response includes the display name
        and other details about each product, and lists the products in the
        proper display order.
      parameters:
        - name: latitude
          in: "body"
```

**Comment by ghillairet** [comment]
It is fixed in master.

![screen shot 2016-01-07 at 14 02 42](https://cloud.githubusercontent.com/assets/148045/12171097/5c494acc-b547-11e5-9a50-d57aecf6f00d.png)

**Comment by borlander** [comment]
I was frequently editing this parameters part of swagger files (to check how the diagram is updated) and I would like to add one note. 
When you already have parameter, e.g,  in: "path" and want to change it to, e.g, in: "header", you normally invoke the code completion AFTER the quote. 

For me invoking the completion as shown at the screenshot (in: &lt;caret&gt;) indeed works, but invoking it after the quote (in: "&lt;caret&gt;) always adds additional quotes, see screencast: 

![bug-42-addition](https://cloud.githubusercontent.com/assets/1390992/12172840/ab85be02-b553-11e5-91f4-c52666877875.gif)

**Comment by ghillairet** [comment]
Yes I guess we should check if the new text will be added between existing quotes or not.

also related #41

**Comment by tfesenko** [comment]
Fixed in general, quotes are not added to string values.
But when I already have them I invoke content assist as it's shown in https://github.com/ModelSolv/SwagEdit/issues/42#issuecomment-169679892 , content-assist does not provide any proposals:
<img width="267" alt="screen shot 2016-01-14 at 12 16 18 pm" src="https://cloud.githubusercontent.com/assets/644582/12331693/a1d95598-bab8-11e5-8e0f-f132cadc1c5f.png">

**Comment by tedepstein** [comment]
@borlander wrote:

> When you already have parameter, e.g, in: "path" and want to change it to, e.g, in: "header", you normally invoke the code completion AFTER the quote.

@tfesenko wrote:

> when I already have them I invoke content assist as it's shown in #42 (comment) , content-assist does not provide any proposals

Is it really true that you'd normally invoke code assist _after_ the opening quote?  I don't do this, and I wouldn't expect it to work.  So I'm questioning whether this is a really important requirement for our current release.

Also please note that this issue is closed.  So if we do want to do further work on it, we should either re-open it, or add a new issue.
