### ISSUE TITLE
Installation failure on Oxygen

### ISSUE THREAD

**Issue by nkolban** [RepreZen/KaiZen-OpenAPI-Editor#425]
I'm trying to install Kaizen on a fresh Oxygen/Eclipse installation.  When I attempt to install through the Market place, we error out with the text:

```
An error occurred while collecting items to be installed
session context was:(profile=epp.package.javascript, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,com.reprezen.swagedit,0.8.0.201710301020
No repository found containing: osgi.bundle,com.reprezen.swagedit.core,0.8.0.201710301020
No repository found containing: org.eclipse.update.feature,com.reprezen.swagedit.feature,0.8.0.201710301020
No repository found containing: osgi.bundle,com.reprezen.swagedit.openapi3,0.8.0.201710301020
```

![image](https://user-images.githubusercontent.com/3421732/33682673-d5c7954e-da8d-11e7-9ace-9983ba976478.png)

**Comment by tfesenko** [comment]
Hi @nkolban ! Thanks for reporting this issue. I am investigating it. 
In the meantime, you can install KaiZen OpenAPI Editor using an update site as described here: https://github.com/RepreZen/KaiZen-OpenAPI-Editor/blob/master/README.md#installing-from-the-update-site

**Comment by tfesenko** [comment]
@nkolban , a correction: please follow the instructions provided above with this update site:
* http://products.reprezen.com/swagedit/0.8.0.201710301020/ 

We are having problems with http://products-internal.reprezen.com/swagedit/latest/

**Comment by nkolban** [comment]
Thank you my friend.  The URL http://products.reprezen.com/swagedit/0.8.0.201710301020/ worked just fine for me with a manual application add in Eclipse Oxygen.

**Comment by tfesenko** [comment]
Glad to hear that the update site worked for you, @nkolban!
BTW, we fixed the marketplace entry. Thanks again for reporting this issue.
