### ISSUE TITLE
Folded code blocks unfold spontaneously on edit

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#433]
KZOE supports code folding, but apparently it's fragile.  A user [reports here](https://support.reprezen.com/a/tickets/358) that it tends to unfold spontaneously. I have observed this happening with code assist, or sometimes with just routine editing in RepreZen API Studio.  I have not tested this with KZOE independent of API Studio. 

@ghillairet , it would be helpful to have a look at this and determine a rough effort estimate to fix it.

**Comment by tfesenko** [comment]
Similar issue: #418: Folded sections auto expanding when adding content. 
I started work on it four months ago on branch https://github.com/RepreZen/KaiZen-OpenAPI-Editor/commits/task/418 . I don't remember why I did not create a PR for it. Probably wanted to estimate impact on performance first.

**Comment by tedepstein** [comment]
It seems this issue is a duplicate, so I'll close it, and move some comments over to #418.
