### ISSUE TITLE
Beautify the default color scheme

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#44]
The default color scheme is not as pretty as it might be.  I'll play with this a bit and make some more specific suggestions.

**Comment by tedepstein** [comment]
In API Studio, we are using the Eclipse Color Theme plugin, with a dark color theme (inkpot) selected.  For general use outside of API studio, we probably should not assume a dark background, so we should choose colors that works with a light background.

**Comment by ghillairet** [comment]
Note that eclipse color theme plugins requires that mappings for specific editors are contributed (see https://github.com/eclipse-color-theme/eclipse-color-theme/wiki/Contributing). The mapping for YEdit is already present in the current version of eclipsecolortheme, that explains why SwagEdit works well with it.

Also the general use of this color theme plugin is that users choose a theme and then all their editors use that particular theme.

The default theme from Eclipse is the one with white background and purple color for keywords (see Java editor for ex). Maybe this one should be use.

**Comment by tedepstein** [comment]
@ghillairet , can you paste a screenshot with SwagEdit in the default theme?

**Comment by ghillairet** [comment]
So the default theme for YEdit does not use similar colors as the Eclipse default. Choosing Default theme in eclipse color themes preferences makes editors use their defaults preferences.

Looks like this for YEdit (and SwagEdit)

![screen shot 2016-01-07 at 16 44 32](https://cloud.githubusercontent.com/assets/148045/12174756/c0d640a0-b55e-11e5-9d73-07c2bf3a452c.png)

I was thinking we could provide default preferences that would look like that

![screen shot 2016-01-07 at 16 46 03](https://cloud.githubusercontent.com/assets/148045/12174763/d009aa6c-b55e-11e5-872d-2636b3daa2c6.png)

**Comment by tedepstein** [comment]
Yes, I think that second screenshot looks good.  Let's go with that color scheme as the default.

**Comment by tfesenko** [comment]
After having merged the PR, I noticed that what I see is slightly different from the screenshot above:
<img width="703" alt="screen shot 2016-01-20 at 4 18 50 pm" src="https://cloud.githubusercontent.com/assets/644582/12463530/f4649506-bf91-11e5-9db6-48e3617db073.png">

Note that boolean values ("Constants") are blue in my screenshot, but they are green on Guillaume's.

**Comment by tedepstein** [comment]
@ghillairet , it also looks to me like the purple/violet color is not the same as in your screenshot.  Can we make the default colors match your earlier sceenshot?

**Comment by ghillairet** [comment]
I took the colors from the default Java editor, in the first screenshot I took colors that look like it.

Here what it looks like on my screen.

![screen shot 2016-01-21 at 18 55 43](https://cloud.githubusercontent.com/assets/148045/12489463/c75c26a2-c070-11e5-9a78-0de02c0d498f.png)

**Comment by ghillairet** [comment]
For info, default colors for SwagEdit are defined here https://github.com/ModelSolv/SwagEdit/blob/master/com.reprezen.swagedit/src/com/reprezen/swagedit/preferences/SwaggerPreferenceInitializer.java#L21

**Comment by tedepstein** [comment]
I confirmed that the purple color matches Eclipse's default for Java keywords.  Boolean constants are blue, also apparently consistent with Java's color scheme.

@tfesenko , I'm satisfied with these colors.  If you approve, please close this.
