### ISSUE TITLE
Cannot create a new project

### ISSUE THREAD

**Issue by projectxmaker** [RepreZen/KaiZen-OpenAPI-Editor#452]
Hi,

I've installed Eclipse Photon 4.8.0, Kaizen OpenAPI Editor (from [HERE](https://marketplace.eclipse.org/content/kaizen-openapi-editor)).

I tried to create a new project with both OpenAPI v3 Spec or Swagger v2 Spec, but it doesn't work.

It keeps showing an error:  The specified project does not exist.

I'm sure /Users/pat/Documents/test exists.

Screenshot here: https://drive.google.com/file/d/1-N1m8fixUWnpd4TVFSUGAFTTBWMAcEse/view?usp=sharing

Thanks for any help.

**Comment by tfesenko** [comment]
Hi @projectxmaker , the "OpenAPI v3 Spec" and "Swagger v2 Spec" wizards create Swagger/OAS files in an **existing** Eclipse project, just a folder is not enough. You can create a new empty project by using the "File > New > Project... > General > Project" wizard:
<img width="561" alt="screen shot 2018-07-02 at 2 48 37 pm" src="https://user-images.githubusercontent.com/644582/42180958-29cb6f18-7e07-11e8-950c-bf0b1d1bd615.png">

Can you please double-check that a project does exist and create it if it doesn't?

If the project does exist and you are still seeing this error, can you please send us  your[ Eclipse Error Log](https://wiki.eclipse.org/FAQ_Where_can_I_find_that_elusive_.log_file%3F)?

**Comment by projectxmaker** [comment]
Hi @tfesenko,

The issue is resolved.

Thank you very much :")

Regards,
