### ISSUE TITLE
Code assist not working on Parameter & Response References

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#48]
Where the schema allows for a $ref:, I hoped code assist would help me pick one of the available values, but it doesn't seem to be implemented.  Is this in scope for the first release, or is it deferred?

**Comment by tfesenko** [comment]
It's fixed in https://github.com/ModelSolv/SwagEdit/pull/39

**Comment by tedepstein** [comment]
Changed the name of this issue to be more specific:  The current implementation of code assist works well for references to Swagger Schema Objects, defined in the Swagger Object's Definitions Object.  It displays a set of suggestions appropriate for a `$ref` used as the `schema` of a Parameter Object or Response Object.

There are two other context categories where an internal Reference Object can be used:
- as a Parameter, referencing a Parameter Definition in the Swagger Object's Parameters Definitions Object
- as a Response, referencing a Response Definition in the Swagger Object's Responses Definitions Object

Code assist should be able to help here as well, showing the appropriate choices in context.

**Comment by tedepstein** [comment]
This is resolved.  Closing.
