### ISSUE TITLE
 Internal error occurred during: "Update KaiZen Editor validation markers"

### ISSUE THREAD

**Issue by ksclarke** [RepreZen/KaiZen-OpenAPI-Editor#516]
I'm getting the following exception when I open our YAML OpenAPI file (which was previously working without any errors -- I'm guessing a plugin or related Eclipse package upgrade is the problem since the file hasn't changed):
```
An internal error occurred during: "Update KaiZen Editor validation markers".
Bad type on operand stack
Exception Details:
  Location:
    com/reprezen/jsonoverlay/JsonLoader.<clinit>()V @17: invokespecial
  Reason:
    Type 'com/reprezen/jsonoverlay/parser/LocationRecorderYamlFactory' (current frame, stack[2]) is not assignable to 'com/fasterxml/jackson/core/JsonFactory'
  Current Frame:
    bci: @17
    flags: { }
    locals: { }
    stack: { uninitialized 10, uninitialized 10, 'com/reprezen/jsonoverlay/parser/LocationRecorderYamlFactory' }
  Bytecode:
    0000000: bb00 3359 b700 34b3 001d bb00 3559 b200
    0000010: 1db7 0036 b300 21b2 0021 b200 37b6 0038
    0000020: 57b1
```
My version of Eclipse: 2018-12 (4.10.0)

I've uninstalled and reinstalled the KaiZen plugin from the update site: https://github.com/RepreZen/KaiZen-OpenAPI-Editor/blob/master/README.md#installing-from-the-update-site (so have the latest version there).

The problematic schema is available at: https://raw.githubusercontent.com/UCLALibrary/bucketeer/master/src/main/resources/bucketeer.yaml

**Comment by ksclarke** [comment]
Additional information, workaround: upgrading to the latest version of Eclipse solves the problem. You may choose to close given that if you'd like.

**Comment by tedepstein** [comment]
@ksclarke , thanks for the error report. We recently updated KaiZen Editor to the Oxygen target platform. Which version of Eclipse were you using when you encountered this issue?

**Comment by ksclarke** [comment]
the 2018-12 version

**Comment by tedepstein** [comment]
@ksclarke , thank you. I will take your suggestion and close this issue for now. If we find that it is happening in other versions of Eclipse, we will reopen and address it then.
