### ISSUE TITLE
Only Swagger v2 features work, not OpenAPI v3

### ISSUE THREAD

**Issue by aivarannamaa** [RepreZen/KaiZen-OpenAPI-Editor#519]
After I replaced my Eclipse 2019-03 running on Oracle Java 8  to Eclipse 2019-06 runnig on Open JDK 11, KaiZen doesn't support OpenAPI features anymore:

![image](https://user-images.githubusercontent.com/1802/64002022-c6b2cd00-cb11-11e9-9e7b-3dd0afc23a64.png)

First marker on the screenshot says:

> Multiple markers at this line
> - object has missing required properties "swagger"
> - object has properties "components", "openapi" which are not allowed

In the new file dialog, under KaiZen there is only "Swagger v2 spec". 

Plug-in version is   0.8.0.201907182108. Platform is Ubuntu 18.04 64-bit. I installed the plug-in via Marketplace

**Comment by tedepstein** [comment]
Hi @aivarannamaa . I have tested this on Windows by installing the [Java EE distro](https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2019-06/R/eclipse-jee-2019-06-R-win32-x86_64.zip) of Eclipse 2019-06, and updating the Eclipse.ini to force it to run on Java 11.

I am not seeing the issues you documented here. We don't generally test on Linux, but will look into this when we can. Meanwhile, it would be helpful if you can please [send your application log file](https://support.reprezen.com/support/solutions/articles/24000000130-sending-the-application-error-log-to-reprezen-support) so we can see what's happening.

**Comment by aivarannamaa** [comment]
I think I found relevant log entry:

```
org.osgi.framework.BundleException: Could not resolve module: com.reprezen.swagedit.openapi3 [546]
  Unresolved requirement: Require-Bundle: com.github.eclipsecolortheme; resolution:="optional"
  Unresolved requirement: Require-Bundle: com.reprezen.kaizen.openapi-parser
    -> Bundle-SymbolicName: com.reprezen.kaizen.openapi-parser; bundle-version="4.0.4"
       com.reprezen.kaizen.openapi-parser [543]
         Unresolved requirement: Import-Package: com.reprezen.jsonoverlay.gen; resolution:="optional"
         Unresolved requirement: Import-Package: javax.mail.internet
           -> Export-Package: javax.mail.internet; bundle-symbolic-name="com.sun.mail.javax.mail"; bundle-version="1.6.1"; version="1.6.0"; uses:="javax.activation,javax.mail"
              com.sun.mail.javax.mail [547]
                Unresolved requirement: Import-Package: javax.activation

	at org.eclipse.osgi.container.Module.start(Module.java:457)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.run(ModuleContainer.java:1820)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1813)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1769)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1735)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
```

Session data:

```
eclipse.buildId=4.12.0.I20190605-1800
java.version=11.0.4
java.vendor=Ubuntu
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -data file:/toll/workspace_impulss/ -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.java.product
```

**Comment by aivarannamaa** [comment]
Seems to be related to #495

**Comment by aivarannamaa** [comment]
I was able to get it working by uninstalling from Marketplace and reinstalling from "Help => Install new software"

**Comment by tedepstein** [comment]
@aivarannamaa , thanks for the additional details. I think we have a solution for this. It may be a few days, maybe as long as a week or two before this gets released, since it involves restructuring dependencies in KaiZen Editor. This work was necessary to simplify our CI/CD build pipeline, but solving the Java 11 compatibility issue is an additional benefit.

**Comment by tedepstein** [comment]
@aivarannamaa , we have a new KaiZen OpenAPI Editor release 0.8.0.201909171245 available on Eclipse Marketplace, which might resolve this issue for you. Please give it a try at your convenience, and let us know if it fixes the problem for you.

**Comment by aivarannamaa** [comment]
In the meanwhile I upgraded to Eclipse 2019-09. Now I can use Openapi v3 features even if I install from the marketplace. Thank you!
