### ISSUE TITLE
Standardize on "Swagger Spec" as the name of the source file

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#53]
Some inconsistencies noted:
- New->Other->Swagger offers "Swagger File", which brings up the wizard to create a new Swagger Spec.  The menu command should say "Swagger Spec"
  - Title is "Swagger" - should be "New Swagger Spec"
  - Description is "This wizard creates a new file with *.yaml extension that can be opened by the swagger editor."  Should be: "This wizard creates a new Swagger Spec in YAML format, which can be opened in SwagEdit."

**Comment by ghillairet** [comment]
I changed the wizard title to Swagger Spec and New Swagger Spec

![screen shot 2016-01-07 at 13 37 55](https://cloud.githubusercontent.com/assets/148045/12195366/06550970-b5f7-11e5-833a-e9b9f048812b.png)

Also changed the wizard description

![screen shot 2016-01-07 at 13 38 57](https://cloud.githubusercontent.com/assets/148045/12195368/0799787a-b5f7-11e5-94e0-7b43bcca212f.png)

**Comment by tfesenko** [comment]
Description is updated for the wizard page, but there is no description on the wizard:
<img width="554" alt="screen shot 2016-01-08 at 4 18 21 pm" src="https://cloud.githubusercontent.com/assets/644582/12209811/8822d6f4-b623-11e5-8e70-5793d770deed.png">

Many Eclipse wizards provide descriptions, e.g. Oomph and JDT:
<img width="561" alt="screen shot 2016-01-08 at 4 20 03 pm" src="https://cloud.githubusercontent.com/assets/644582/12209839/b9be45cc-b623-11e5-81c8-04f3faed220e.png">

**Comment by tfesenko** [comment]
Labels are updated, except for the missing description of the wizard, see comment above

**Comment by tedepstein** [comment]
Good catch, @tfesenko!  I recommend this descriptive text:

> Create a new Swagger Spec:  an API description as defined by the OpenAPI Specification.

**Comment by tfesenko** [comment]
A new wizard description, I took a liberty to commit directly to the master for such a trivial change:
<img width="576" alt="screen shot 2016-01-27 at 9 57 53 pm" src="https://cloud.githubusercontent.com/assets/644582/12633613/19eb9d88-c541-11e5-932c-f878aaa9177b.png">

**Comment by tedepstein** [comment]
Closing.
