### ISSUE TITLE
Change preferences page to "SwagEdit"

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#56]
The preferences page is currently called "Swagger".  The name of the specification has changed from Swagger to the [Open API Specification](https://github.com/OAI/OpenAPI-Specification), with the creation of the [Open API Initiative](https://openapis.org/).

SwagEdit is a fine name, and I don't think we want to change it, unless someone really wants to change the name to tOASter or rOAStEd, or some other clever name with OAS.  (Just kidding.  Please, let's stick with SwagEdit!)

But I think it's better to use the product name, not the branded and now outdated specification name, as the preferences category.

**Comment by ghillairet** [comment]
Fixed
