### ISSUE TITLE
Code assist should support typeahead with dynamic filtering

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#58]
The code assist feature in other Eclipse editors supports two useful behaviors that we should add to SwagEdit: 
1.  After invoking code assist, you can start typing, and the list of suggestions will remain visible, filtered to show the suggestions that start with the substring you entered.
2. If you invoke code assist with one or more characters already typed, immediately to the left of the insertion point, and then invoke code assist, the suggestion list will be pre-filtered to show matching suggestions.

**Comment by tedepstein** [comment]
I noticed that filtering works in some contexts, but not others.  It appears to work fine on a method.  Typing a 'd' filters down to the keywords "deprecated" and "description".  But it doesn't work on a parameter item.  Typing a letter just closes the code assist suggestions, instead of filtering it.

**Comment by tedepstein** [comment]
Making this one high priority.  Some users are starting to notice that this doesn't work as expected, and in some cases they have the impression that code assist simply doesn't work.

**Comment by ghillairet** [comment]
I have looked at this. The problem is that in some cases, the yaml parser fails to parse the content of the document after the user enters a character and invoke content assist. The document becomes invalid while the user enters those new characters.
We need what is returned by the yaml parser to compute the content assist proposals, but in those cases maybe we should allow the proposals provider to use the previous state of the document.

**Comment by tfesenko** [comment]
As @ghillairet mentioned above this task is more difficult than just filtering a list of strings based on a prefix. We have to deal with a parser results for invalid models. For example, Xtext generates a special lightweight Antlr parser (`org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser`) and lexer tailored for content assist.
Finding a right approach for implementation of this feature can take some time.

**Comment by tedepstein** [comment]
@tfesenko @ghillairet, thanks for the input.  I continue to think that this is really important, and we should try to find a way to make it work.  I'm quite open to considering some creative solutions for this, if you have any.

**Comment by tedepstein** [comment]
Not sure if @ghillairet's most recent commit, [introducing a unified JSON model](https://github.com/RepreZen/SwagEdit/commit/e0d612d802e43792b118a4287581b08d25d23897), helps with typeahead.  But I had a couple of thoughts about this that I wanted to record here, when we're ready to get back to it:
- Could we suspend validation while the code assist UI is displayed? So if the user invokes code assist, starts typing, and introduces a validation error while typing, it shouldn't disrupt the functionality of code assist, which is the user's current focus.  There are other typeahead scenarios that this may not address, such as typing a partial string and then invoking code assist; but it would still be a big improvement.
- Can we cache the most recent valid state of the document, and present this when the user invokes code assist?  This could address that other case, where the user enters a partial string, which introduces an error, and then invokes code assist.  I think this is what Guillaume referred to in [this previous comment](https://github.com/RepreZen/SwagEdit/issues/58#issuecomment-235910077).

**Comment by ghillairet** [comment]
@tedepstein Actually I've done something in my latest PR that helps with that issue. (I should update the PR comment I haven't wrote all reasons that made me implement that, but the use of a model is not the reason for that fix)

 It is done exactly on that line https://github.com/RepreZen/SwagEdit/pull/176/commits/e0d612d802e43792b118a4287581b08d25d23897#diff-8bef65b0311b7566e89920c6a04c4972R38 What I do is that I only parse the document until the position of the user's cursor, and remove what he already typed. I found that it makes the content assist work in cases where it didn't before.

**Comment by tfesenko** [comment]
Note (on task/58 branch):
Typeahead work well at the end of a line:
<img width="341" alt="screen shot 2016-10-04 at 5 08 03 pm" src="https://cloud.githubusercontent.com/assets/644582/19092564/41f4fcc8-8a55-11e6-8c06-6c4a73c0fc7f.png">
But it does not work in the middle of a line:
<img width="335" alt="screen shot 2016-10-04 at 5 08 17 pm" src="https://cloud.githubusercontent.com/assets/644582/19092572/4fef795c-8a55-11e6-863a-f52fc72ba0d8.png">

I am not sure if the latter is a common scenario though...

**Comment by tfesenko** [comment]
Except a limitation noted above (the cursor should be at the very end of the line) I did not notice any issues related to typeahead (all on the task branch).

I submitted several general content-assist bugs, the most important one is #217 "Code-assist for schema properties is incomplete". It's hard to verify typeahead for schema definitions when content-assist shows only generic `_key_`proposals...

IMO, the `paths` work much better than schema definitions.

**Comment by tfesenko** [comment]
Typeahead works quite well (with an exception of #217 "Code-assist for schema properties is incomplete").
I found a new bug: code-assist shows code templates that don't start with the provided prefix:
<img width="436" alt="screen shot 2016-10-05 at 6 03 43 pm" src="https://cloud.githubusercontent.com/assets/644582/19133485/733b4540-8b26-11e6-815f-2edb8a4ba4ad.png">

**Comment by tedepstein** [comment]
@tfesenko wrote:

> code-assist shows code templates that don't start with the provided prefix:

I think we could extract that bug to a new issue, which doesn't need to be considered high-priority. @tfesenko , if you agree, please extract it and close this one.

**Comment by tedepstein** [comment]
@tfesenko , @ghillairet , should we close this issue?

**Comment by ghillairet** [comment]
I think yes.
