### ISSUE TITLE
Syntax highlighting: Support a preferences screen to specify colors for all relevant Swagger language element types

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#6]
@ghillairet defined an empty preferences page for Swagger:
<img width="665" alt="screen shot 2015-10-06 at 5 21 34 pm" src="https://cloud.githubusercontent.com/assets/644582/10323087/e0da972e-6c4e-11e5-9843-0dde636c0b63.png">
YEdit provides a "Color Preferences page" for similar purposes:
<img width="652" alt="screen shot 2015-10-06 at 5 21 45 pm" src="https://cloud.githubusercontent.com/assets/644582/10323088/e2b4abc0-6c4e-11e5-8800-a527bee8a780.png">

**Comment by tedepstein** [comment]
@tfesenko , can we close this?

**Comment by tfesenko** [comment]
Yes, we can close it. 
Note that internally we share color preferences with YEdit. So, if you modify colors in YEdit preferences page, these values will be updated for SwagEdit too. It was done intentionally for consistency with other YEdit editors.
