### ISSUE TITLE
Publish SwagEdit to Eclipse Marketplace

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#65]
It's easier for the users to install a tool from the Eclipse Marketplace than to entertain with the help/install new software and update site URLs.

**Comment by tedepstein** [comment]
Another good catch, @tfesenko !  I'll create a new milestone for this one, because it relates to the open source release of SwagEdit, not the Swagger Interop release of API Studio.

**Comment by tfesenko** [comment]
[Eclipse Marketplace Quickstart](http://marketplace.eclipse.org/quickstart)

**Comment by paulvi** [comment]
Do you need help with this? I can publish quick

**Comment by tfesenko** [comment]
@paulvi , thank you for proposing help. We are not quite ready to do it yet, but we’ll do it shortly!

**Comment by paulvi** [comment]
It will be the first anniversary from opening the issue soon...

**Comment by tedepstein** [comment]
Now KaiZen-OpenAPI-Editor (formerly SwagEdit) is available on Eclipse Marketplace.  

https://marketplace.eclipse.org/content/kaizen-openapi-editor
