### ISSUE TITLE
Code assist keyword suggestions under paths all say "undefined" 

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#73]
The "undefined" suffix after each keyword seems to indicate a problem, or an incomplete configuration.  

What is supposed to appear there?  If it's something like a keyword description, let's provide the descriptions. Otherwise, if it's not ever going to show something useful, maybe we can change the code assist presentation to omit that suffix.

<img width="967" alt="reprezen - swagedit template testmodelsfoodbank yaml - reprezen api studio_2016-01-13_12-23-49" src="https://cloud.githubusercontent.com/assets/692813/12304765/33fc7212-b9ff-11e5-8955-cfa2ab72baae.png">

**Comment by tedepstein** [comment]
@tfesenko , @daffinm , I put this in scope for our current milestone, and tentatively marked it "high priority" as it will affect demos and videos.  Miles, do you agree this is important?

**Comment by ghillairet** [comment]
Fixed in branch feature/73

![screen shot 2016-01-14 at 12 07 57](https://cloud.githubusercontent.com/assets/148045/12323015/52393fda-bab8-11e5-9d28-90a682021388.png)

Also if no type is to be found, it uses the key holding the schema to name it, see it used for vendorExtension.

**Comment by tedepstein** [comment]
Looks good!
