### ISSUE TITLE
SwagEdit provider should be specified

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#79]
<img width="1079" alt="screen shot 2016-01-14 at 10 33 32 am" src="https://cloud.githubusercontent.com/assets/644582/12328730/a96e70da-baaa-11e5-98f4-5104422f5bad.png">

**Comment by tedepstein** [comment]
Provider should be specified as "ModelSolv, Inc. d.b.a. RepreZen"

**Comment by tfesenko** [comment]
Fixed in https://github.com/RepreZen/SwagEdit/pull/110
