### ISSUE TITLE
Support folding of elements

### ISSUE THREAD

**Issue by ghillairet** [RepreZen/KaiZen-OpenAPI-Editor#8]
The swagger online editor supports collapsing of elements, this can also be done in eclipse with folding, see https://www.eclipse.org/articles/Article-Folding-in-Eclipse-Text-Editors/folding.html

**Comment by tedepstein** [comment]
Good idea.  I think we should do this in a later phase.

**Comment by ghillairet** [comment]
There is now basic support for folding. It works only on root elements for now. It can be tested in the develop branch.

**Comment by tfesenko** [comment]
Fixed.
