### ISSUE TITLE
YEdit Format command removes YAML comments: fix or disable auto-format

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#99]
As reported here, auto-format in YEdit removes all YAML comments from the source file, without warning:

   https://github.com/oyse/yedit/issues/15

IMO, YAML comments are important, and we should disable auto-format until we can fix this bug.

**Comment by tfesenko** [comment]
@tedepstein , can you please clarify what is expected from the fix? 
To me. "Auto-Format" sounds like an action which happens automatically, which is not explicitly invoked by the user. I don't see that format is invoked automatically. 

If I _manually_ call formatting the the comments are removed as noted in the issue. 
Should I remove the action from the context menu and possibly other entries in UI, and also remove a key binding?

**Comment by tedepstein** [comment]
I meant manually invoked formatting.  We should remove the shortcut key binding (normally ctrl+shift+f on Windows), and the context menu item.  If you find other UI entries, you should probably remove those too.

**Comment by tfesenko** [comment]
The _good_ **news** is that it's always "Ctrl+Shift+F", even on Mac where it should be "CMD+shift-F".
 The regular key binding for code formatting does not do anything in YEdit on Mac

**Comment by tedepstein** [comment]
@tfesenko , we fixed this in API Studio.
https://github.com/ModelSolv/RepreZen/pull/873/files

Can the same fix be applied here?

**Comment by tfesenko** [comment]
@tedepstein  asked:

> we fixed this in API Studio. Can the same fix be applied here?

We fixed in by overriding preferences in our RCP application so the key binding is disabled. We can't apply the same fix as is, but we can think of variations, e.g. create a SwagEdit perspective and change preferences when the user switches to our perspective.

Another approach is to contact YEdit and see if we can ask them to disable the action by default (I don't know if they will be thrilled to do it though).

The users can manually disable the binding too. We can add this issue and a step-by-step solution to our documentation.

**Comment by tedepstein** [comment]
> The users can manually disable the binding too. We can add this issue and a step-by-step solution to our documentation.

I think that's the best approach for now.  If you can please write up a short paragraph or two in the Readme, I'll review.

**Comment by tfesenko** [comment]
@tedepstein , I added a description how to disable the key binding to https://github.com/RepreZen/SwagEdit/blob/master/README.md#troubleshooting
<img width="954" alt="yedit_disableformat" src="https://cloud.githubusercontent.com/assets/644582/13615520/b0411e3a-e543-11e5-93d7-dd4917be20da.png">

**Comment by tedepstein** [comment]
@tfesenko , your screenshot and additions to the README look good.  I think this is "fixed", to the extent we're able to address the issue in the SwagEdit context.  Not much more we can do now, therefore closing.  Please reopen if you think I've missed anything.
